package model809

// Code generated by ../../generators/models/models.go. DO NOT EDIT.
// You can regenerate it by running 'go generate ./models' from the directory above.

import (
	"github.com/andig/gosunspec"
	"github.com/andig/gosunspec/typelabel"
	"github.com/andig/gosunspec/types"
)

// Block809 - Flow Battery Stack Model -

const (
	ModelID          = 809
	ModelLabel       = "Flow Battery Stack Model"
	ModelDescription = ""
)

const (
	CellTBD  = "CellTBD"
	StackTBD = "StackTBD"
)

type Block809Repeat struct {
	CellTBD uint16 `sunspec:"offset=0,len=1"`
}

type Block809 struct {
	StackTBD uint16 `sunspec:"offset=0,len=1"`

	Repeats []Block809Repeat
}

func (block *Block809) GetId() sunspec.ModelId {
	return ModelID
}

func init() {
	types.RegisterModel(&types.Model{
		Id:          ModelID,
		Name:        "flow_battery_stack",
		Label:       "Flow Battery Stack Model",
		Description: "",
		Length:      2,
		Blocks: []types.Block{
			{
				Length: 1,
				Type:   types.BlockFixed,
				Points: []types.Point{
					{Id: StackTBD, Offset: 0, Type: typelabel.Uint16, Length: 1, Mandatory: true, Label: "Stack Points To Be Determined", Description: ""},
				},
			},
			{Name: "cell",
				Length: 1,
				Type:   types.BlockRepeating,
				Points: []types.Point{
					{Id: CellTBD, Offset: 0, Type: typelabel.Uint16, Length: 1, Mandatory: true, Label: "Cell Points To Be Determined", Description: ""},
				},
			},
		}})
}
