package model706

// Code generated by ../../generators/models.go. DO NOT EDIT.
// You can regenerate it by running 'go generate ./models' from the directory above.

import (
	"github.com/andig/gosunspec"
	"github.com/andig/gosunspec/smdx"
	"github.com/andig/gosunspec/typelabel"
)

// Block706 - DERVolt-Watt - DER Volt-Watt model.

const (
	ModelID          = 706
	ModelLabel       = "DERVolt-Watt"
	ModelDescription = "DER Volt-Watt model."
)

const (
	ActPt       = "ActPt"
	AdptCrvReq  = "AdptCrvReq"
	AdptCrvRslt = "AdptCrvRslt"
	DeptRef     = "DeptRef"
	DeptRef_SF  = "DeptRef_SF"
	Ena         = "Ena"
	NCrv        = "NCrv"
	NPt         = "NPt"
	ReadOnly    = "ReadOnly"
	RspTms      = "RspTms"
	RspTms_SF   = "RspTms_SF"
	RvrtCrv     = "RvrtCrv"
	RvrtRem     = "RvrtRem"
	RvrtTms     = "RvrtTms"
	V_SF        = "V_SF"
)

type Block706Repeat struct {
	ActPt    uint16         `sunspec:"offset=0,len=1,access=rw"`
	DeptRef  sunspec.Enum16 `sunspec:"offset=1,len=1,access=rw"`
	RspTms   uint32         `sunspec:"offset=2,len=2,sf=RspTms_SF,access=rw"`
	ReadOnly sunspec.Enum16 `sunspec:"offset=4,len=1,access=r"`
}

type Block706 struct {
	Ena         sunspec.Enum16      `sunspec:"offset=0,len=1,access=rw"`
	AdptCrvReq  uint16              `sunspec:"offset=1,len=1,access=rw"`
	AdptCrvRslt sunspec.Enum16      `sunspec:"offset=2,len=1,access=r"`
	NPt         uint16              `sunspec:"offset=3,len=1,access=r"`
	NCrv        uint16              `sunspec:"offset=4,len=1,access=r"`
	RvrtTms     uint32              `sunspec:"offset=5,len=2,access=rw"`
	RvrtRem     uint32              `sunspec:"offset=7,len=2,access=r"`
	RvrtCrv     uint16              `sunspec:"offset=9,len=1,access=rw"`
	V_SF        sunspec.ScaleFactor `sunspec:"offset=10,len=1,access=r"`
	DeptRef_SF  sunspec.ScaleFactor `sunspec:"offset=11,len=1,access=r"`
	RspTms_SF   sunspec.ScaleFactor `sunspec:"offset=12,len=1,access=r"`

	Repeats []Block706Repeat
}

func (block *Block706) GetId() sunspec.ModelId {
	return ModelID
}

func init() {
	smdx.RegisterModel(&smdx.ModelElement{
		Id:     ModelID,
		Name:   "DERVoltWatt",
		Length: 18,
		Blocks: []smdx.BlockElement{
			{
				Length: 13,
				Points: []smdx.PointElement{
					{Id: Ena, Offset: 0, Type: typelabel.Enum16, Access: "rw", Length: 1, Mandatory: true, Label: "Module Enable", Description: "Volt-Watt control enable."},
					{Id: AdptCrvReq, Offset: 1, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true, Label: "Adopt Curve Request", Description: "Index of  curve points to adopt. First curve index is 1."},
					{Id: AdptCrvRslt, Offset: 2, Type: typelabel.Enum16, Access: "r", Length: 1, Mandatory: true, Label: "Adopt Curve Result", Description: "Result of last adopt curve operation."},
					{Id: NPt, Offset: 3, Type: typelabel.Uint16, Access: "r", Length: 1, Mandatory: true, Label: "Number Of Points", Description: "Number of curve points supported."},
					{Id: NCrv, Offset: 4, Type: typelabel.Uint16, Access: "r", Length: 1, Mandatory: true, Label: "Stored Curve Count", Description: "Number of stored curves supported."},
					{Id: RvrtTms, Offset: 5, Type: typelabel.Uint32, Access: "rw", Length: 2, Label: "Reversion Timeout", Description: "Reversion time in seconds.  0 = No reversion time."},
					{Id: RvrtRem, Offset: 7, Type: typelabel.Uint32, Access: "r", Length: 2, Label: "Reversion Time Remaining", Description: "Reversion time remaining in seconds."},
					{Id: RvrtCrv, Offset: 9, Type: typelabel.Uint16, Access: "rw", Length: 1, Label: "Reversion Curve", Description: "Default curve after reversion timeout."},
					{Id: V_SF, Offset: 10, Type: typelabel.ScaleFactor, Access: "r", Length: 1, Mandatory: true, Label: "Voltage Scale Factor", Description: "Scale factor for curve voltage points."},
					{Id: DeptRef_SF, Offset: 11, Type: typelabel.ScaleFactor, Access: "r", Length: 1, Mandatory: true, Label: "Watt  Scale Factor", Description: "Scale factor for curve watt points."},
					{Id: RspTms_SF, Offset: 12, Type: typelabel.ScaleFactor, Access: "r", Length: 1, Mandatory: true, Label: "Open-Loop Scale Factor", Description: "Open loop response time scale factor."},
				},
			},
			{Name: "Crv",
				Length: 5,
				Type:   "repeating",
				Points: []smdx.PointElement{
					{Id: ActPt, Offset: 0, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true, Label: "Active Points", Description: "Number of active points."},
					{Id: DeptRef, Offset: 1, Type: typelabel.Enum16, Access: "rw", Length: 1, Mandatory: true, Label: "Dependent Reference", Description: "Curve dependent reference."},
					{Id: RspTms, Offset: 2, Type: typelabel.Uint32, ScaleFactor: "RspTms_SF", Units: "Secs", Access: "rw", Length: 2, Label: "Open Loop Response Time", Description: "Open loop response time."},
					{Id: ReadOnly, Offset: 4, Type: typelabel.Enum16, Access: "r", Length: 1, Label: "Curve Access", Description: "Curve read-write access."},
				},
			},
		}})
}
