// Command xml generates Go SunSpec model packages from the legacy SMDX
// XML model definitions (spec/smdx/*.xml).
//
// It is the XML-driven sibling of generators/json/models.go. Both share
// the same template logic via types.Model; only the loader differs.
package main

import (
	"flag"
	"fmt"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"text/template"

	"github.com/andig/gosunspec/types"
	xmlspec "github.com/andig/gosunspec/types/xml"
)

const file = `
{{define "point"}}{{.Id}} {{.Type|goType}} ` + "`" + `sunspec:"offset={{.Offset}}{{if gt .Length 0}},len={{.Length}}{{end}}{{if ne .ScaleFactor ""}},sf={{.ScaleFactor}}{{end}}{{if ne (printf "%s" .Access) ""}},access={{.Access}}{{end}}"` + "`" + `{{end}}
{{define "model"}}
{{$model := .Model}}
{{$repeats := repeatingBlocks $model}}
{{$multi := gt (len $repeats) 1}}

// Block{{$model.Id}} - {{$model.Label}} - {{$model.Description}}

const (
	ModelID = {{$model.Id}}
	ModelLabel = "{{$model.Label}}"
	ModelDescription = "{{$model.Description}}"
)

const (
{{range (uniqueNames $model)}}   {{.|title}} = "{{.}}"
{{end}}
)

{{range $repeats}}
type Block{{$model.Id}}{{if $multi}}{{.Name|title}}{{end}}Repeat struct {
	{{range .Points}}{{template "point" .}}
{{end}}
}
{{end}}

type Block{{$model.Id}} struct {
{{range (fixedBlocks $model)}}
{{range .Points}}    {{template "point" .}}
{{end}}
	{{end}}
{{if $multi}}{{range $repeats}}
  {{.Name|title}} []Block{{$model.Id}}{{.Name|title}}Repeat
{{end}}{{else}}{{range $repeats}}
  Repeats []Block{{$model.Id}}Repeat
{{end}}{{end}}
}

func (block *Block{{$model.Id}}) GetId() sunspec.ModelId {
  return ModelID
}

func init() {
	types.RegisterModel(&types.Model{
	Id: ModelID,
	Name: "{{$model.Name}}",
	Label: "{{$model.Label}}",
	Description: "{{$model.Description}}",
	Length: {{$model.Length}},
	Blocks: []types.Block{ {{range $model.Blocks}}
			{ {{if gt (len .Name) 0 }}Name: "{{.Name}}",{{end}}
				Length: {{.Length}},
				Type: types.Block{{.Type|blockTypeName}},
				Points: []types.Point{ {{range .Points}}
					{Id: {{.Id|title}},Offset: {{.Offset}},Type: typelabel.{{.Type|title}}{{optF "ScaleFactor" .ScaleFactor}}{{optF "Units" .Units}}{{optF "Access" (printf "%s" .Access)}}{{if gt (.Length) 0}},Length: {{.Length}}{{end}}{{if .Mandatory}},Mandatory: {{.Mandatory}}{{end}}{{if .Label}},Label: "{{.Label|cleanStr}}", Description: "{{.Description|cleanStr}}"{{end}}}, {{end}}
				},
			}, {{end}}
	}})
}
{{end}}
package model{{.Model.Id}}

// Code generated by ../../generators/xml/models.go. DO NOT EDIT.
// You can regenerate it by running 'make spec-xml' from the project root.

import (
	"github.com/andig/gosunspec"
	"github.com/andig/gosunspec/typelabel"
	"github.com/andig/gosunspec/types"
)
{{template "model" .}}
`

const loader = `
package models

// Code generated by ../../generators/xml/models.go. DO NOT EDIT.
// You can regenerate it by running 'make spec-xml' from the project root.

{{$top := .TopPackage}}{{$outdir := .OutDir}}
import (
{{range .Names}}   _ "{{$top}}/{{$outdir}}/{{.}}"
{{end}}
)
`

func main() {
	var smdxDir, outDir, topPackage string
	flag.StringVar(&smdxDir, "smdx-dir", "../../spec/smdx/", "Location of the SMDX XML model definitions directory")
	flag.StringVar(&outDir, "out-dir", "../../models", "Output directory for generated Go model packages")
	flag.StringVar(&topPackage, "top-package", "github.com/andig/gosunspec", "Go module path of the package that will own the generated models")
	flag.Parse()

	entries, err := os.ReadDir(smdxDir)
	if err != nil {
		log.Fatal(err)
	}

	models := []*types.Model{}
	for _, e := range entries {
		name := e.Name()
		if !strings.HasPrefix(name, "smdx_") {
			continue
		}

		f, err := os.Open(filepath.Join(smdxDir, name))
		if err != nil {
			log.Fatal(err)
		}

		fmt.Println(name)
		m, err := xmlspec.Decode(f)
		f.Close()
		if err != nil {
			log.Fatalf("parse %s: %v", name, err)
		}
		if m == nil {
			log.Printf("failed to find any models in %s", name)
			continue
		}
		models = append(models, m)
	}

	if err := os.MkdirAll(outDir, 0o777); err != nil {
		log.Fatal(err)
	}

	t := newTemplate()

	for _, m := range models {
		writeModel(t, m, outDir)
	}
	writeLoader(outDir, topPackage)
}

func newTemplate() *template.Template {
	t := template.New("file")
	t.Funcs(map[string]interface{}{
		"goType": func(sstype string) string {
			switch sstype {
			case "uint16", "uint32", "uint64", "int16", "float32", "int32", "int64", "string":
				return sstype
			case "sunssf":
				return "sunspec.ScaleFactor"
			default:
				return "sunspec." + strings.Title(sstype)
			}
		},
		"repeatingBlocks": func(m *types.Model) []types.Block {
			if len(m.Blocks) == 1 && m.Blocks[0].Type == types.BlockRepeating {
				return m.Blocks
			} else if len(m.Blocks) > 1 {
				return m.Blocks[1:]
			} else {
				return []types.Block{}
			}
		},
		"fixedBlocks": func(m *types.Model) []types.Block {
			if len(m.Blocks) > 0 && m.Blocks[0].Type != types.BlockRepeating {
				return m.Blocks[0:1]
			} else {
				return []types.Block{}
			}
		},
		"blockTypeName": func(bt types.BlockType) string {
			switch bt {
			case types.BlockRepeating:
				return "Repeating"
			default:
				return "Fixed"
			}
		},
		"optF": func(n, v string) string {
			if len(v) > 0 {
				return "," + n + ": \"" + v + "\""
			}
			return ""
		},
		"title": func(in string) string {
			if in == "sunssf" {
				return "ScaleFactor"
			}
			return strings.Title(in)
		},
		"cleanStr": func(s string) string {
			return strings.ReplaceAll(s, "\"", "")
		},
		"uniqueNames": func(m *types.Model) []string {
			seen := map[string]bool{}
			for _, b := range m.Blocks {
				for _, p := range b.Points {
					seen[p.Id] = true
				}
			}
			result := []string{}
			for n := range seen {
				result = append(result, n)
			}
			sort.Strings(result)
			return result
		},
	})
	return template.Must(t.Parse(file))
}

func writeModel(t *template.Template, m *types.Model, outDir string) {
	dir := filepath.Join(outDir, fmt.Sprintf("model%d", m.Id))
	if err := os.MkdirAll(dir, 0o777); err != nil {
		log.Fatalf("%v", err)
	}
	tmpPath := filepath.Join(dir, "model.go.tmp")
	out, err := os.OpenFile(tmpPath, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0o644)
	if err != nil {
		log.Fatal(err)
	}
	if err := t.Execute(out, map[string]interface{}{"Model": m}); err != nil {
		log.Fatalf("template execution failed: %v", err)
	}
	out.Close()
	if outBytes, err := exec.Command("gofmt", "-w", tmpPath).CombinedOutput(); err != nil {
		log.Fatalf("gofmt %s failed: %v\n%s", tmpPath, err, outBytes)
	}
	if err := os.Rename(tmpPath, filepath.Join(dir, "model.go")); err != nil {
		log.Fatalf("replacing model.go failed: %v", err)
	}
}

func writeLoader(outDir, topPackage string) {
	entries, err := os.ReadDir(outDir)
	if err != nil {
		log.Fatal(err)
	}
	names := []string{}
	for _, e := range entries {
		if e.IsDir() && strings.HasPrefix(e.Name(), "model") {
			names = append(names, e.Name())
		}
	}
	sort.Strings(names)

	loaderPath := filepath.Join(outDir, "loader.go")
	out, err := os.OpenFile(loaderPath, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0o644)
	if err != nil {
		log.Fatal(err)
	}
	loaderTpl := template.Must(template.New("loader").Parse(loader))
	if err := loaderTpl.Execute(out, map[string]interface{}{
		"Names":      names,
		"TopPackage": topPackage,
		"OutDir":     filepath.Base(outDir),
	}); err != nil {
		log.Fatal(err)
	}
	out.Close()
	if outBytes, err := exec.Command("gofmt", "-w", loaderPath).CombinedOutput(); err != nil {
		log.Fatalf("gofmt loader failed: %v\n%s", err, outBytes)
	}
}
