package model8

// Code generated by ../../generators/json/models.go. DO NOT EDIT.
// You can regenerate it by running 'make spec' from the project root.

import (
	"github.com/andig/gosunspec"
	"github.com/andig/gosunspec/typelabel"
	"github.com/andig/gosunspec/types"
)

// Block8 - Get Device Security Certificate - Security model for PKI

const (
	ModelID          = 8
	ModelLabel       = "Get Device Security Certificate"
	ModelDescription = "Security model for PKI"
)

const (
	Cert = "Cert"
	Fmt  = "Fmt"
	N    = "N"
)

type Block8Repeat struct {
	Cert uint16 `sunspec:"offset=0"`
}

type Block8 struct {
	Fmt sunspec.Enum16 `sunspec:"offset=0"`
	N   uint16         `sunspec:"offset=1"`

	Repeats []Block8Repeat
}

func (block *Block8) GetId() sunspec.ModelId {
	return ModelID
}

func init() {
	types.RegisterModel(&types.Model{
		Id:          ModelID,
		Name:        "model_8",
		Label:       "Get Device Security Certificate",
		Description: "Security model for PKI",
		Length:      3,
		Blocks: []types.Block{
			{
				Length: 2,
				Type:   types.BlockFixed,
				Points: []types.Point{
					{Id: Fmt, Offset: 0, Type: typelabel.Enum16, Mandatory: true, Label: "Format", Description: "X.509 format of the certificate. DER or PEM."},
					{Id: N, Offset: 1, Type: typelabel.Uint16, Mandatory: true, Label: "N", Description: "Number of registers to follow for the certificate"},
				},
			},
			{Name: "repeating",
				Length: 1,
				Type:   types.BlockRepeating,
				Points: []types.Point{
					{Id: Cert, Offset: 0, Type: typelabel.Uint16, Mandatory: true, Label: "Cert", Description: "X.509 Certificate of the device"},
				},
			},
		}})
}
