package model307

// Code generated by ../../generators/models/models.go. DO NOT EDIT.
// You can regenerate it by running 'go generate ./models' from the directory above.

import (
	"github.com/andig/gosunspec"
	"github.com/andig/gosunspec/typelabel"
	"github.com/andig/gosunspec/types"
)

// Block307 - Base Met - Base Meteorological Model

const (
	ModelID          = 307
	ModelLabel       = "Base Met"
	ModelDescription = "Base Meteorological Model"
)

const (
	ElecFld = "ElecFld"
	PPT     = "PPT"
	Pres    = "Pres"
	RH      = "RH"
	Rain    = "Rain"
	Snw     = "Snw"
	SoilWet = "SoilWet"
	SurWet  = "SurWet"
	TmpAmb  = "TmpAmb"
	WndDir  = "WndDir"
	WndSpd  = "WndSpd"
)

type Block307 struct {
	TmpAmb  int16 `sunspec:"offset=0,len=1,sf=-1"`
	RH      int16 `sunspec:"offset=1,len=1"`
	Pres    int16 `sunspec:"offset=2,len=1"`
	WndSpd  int16 `sunspec:"offset=3,len=1"`
	WndDir  int16 `sunspec:"offset=4,len=1"`
	Rain    int16 `sunspec:"offset=5,len=1"`
	Snw     int16 `sunspec:"offset=6,len=1"`
	PPT     int16 `sunspec:"offset=7,len=1"`
	ElecFld int16 `sunspec:"offset=8,len=1"`
	SurWet  int16 `sunspec:"offset=9,len=1"`
	SoilWet int16 `sunspec:"offset=10,len=1"`
}

func (block *Block307) GetId() sunspec.ModelId {
	return ModelID
}

func init() {
	types.RegisterModel(&types.Model{
		Id:          ModelID,
		Name:        "base_met",
		Label:       "Base Met",
		Description: "Base Meteorological Model",
		Length:      11,
		Blocks: []types.Block{
			{
				Length: 11,
				Type:   types.BlockFixed,
				Points: []types.Point{
					{Id: TmpAmb, Offset: 0, Type: typelabel.Int16, ScaleFactor: "-1", Units: "C", Length: 1, Label: "Ambient Temperature", Description: ""},
					{Id: RH, Offset: 1, Type: typelabel.Int16, Units: "Pct", Length: 1, Label: "Relative Humidity", Description: ""},
					{Id: Pres, Offset: 2, Type: typelabel.Int16, Units: "HPa", Length: 1, Label: "Barometric Pressure", Description: ""},
					{Id: WndSpd, Offset: 3, Type: typelabel.Int16, Units: "mps", Length: 1, Label: "Wind Speed", Description: ""},
					{Id: WndDir, Offset: 4, Type: typelabel.Int16, Units: "deg", Length: 1, Label: "Wind Direction", Description: ""},
					{Id: Rain, Offset: 5, Type: typelabel.Int16, Units: "mm", Length: 1, Label: "Rainfall", Description: ""},
					{Id: Snw, Offset: 6, Type: typelabel.Int16, Units: "mm", Length: 1, Label: "Snow Depth", Description: ""},
					{Id: PPT, Offset: 7, Type: typelabel.Int16, Length: 1, Label: "Precipitation Type", Description: " Precipitation Type (WMO 4680 SYNOP code reference)"},
					{Id: ElecFld, Offset: 8, Type: typelabel.Int16, Units: "Vm", Length: 1, Label: "Electric Field", Description: ""},
					{Id: SurWet, Offset: 9, Type: typelabel.Int16, Units: "kO", Length: 1, Label: "Surface Wetness", Description: ""},
					{Id: SoilWet, Offset: 10, Type: typelabel.Int16, Units: "Pct", Length: 1, Label: "Soil Wetness", Description: ""},
				},
			},
		}})
}
