package model806

// Code generated by ../../generators/json/models.go. DO NOT EDIT.
// You can regenerate it by running 'make spec' from the project root.

import (
	"github.com/andig/gosunspec"
	"github.com/andig/gosunspec/typelabel"
	"github.com/andig/gosunspec/types"
)

// Block806 - Flow Battery Model -

const (
	ModelID          = 806
	ModelLabel       = "Flow Battery Model"
	ModelDescription = ""
)

const (
	BatStTBD = "BatStTBD"
	BatTBD   = "BatTBD"
)

type Block806Repeat struct {
	BatStTBD uint16 `sunspec:"offset=0"`
}

type Block806 struct {
	BatTBD uint16 `sunspec:"offset=0"`

	Repeats []Block806Repeat
}

func (block *Block806) GetId() sunspec.ModelId {
	return ModelID
}

func init() {
	types.RegisterModel(&types.Model{
		Id:          ModelID,
		Name:        "flow_battery",
		Label:       "Flow Battery Model",
		Description: "",
		Length:      2,
		Blocks: []types.Block{
			{
				Length: 1,
				Type:   types.BlockFixed,
				Points: []types.Point{
					{Id: BatTBD, Offset: 0, Type: typelabel.Uint16, Mandatory: true, Label: "Battery Points To Be Determined", Description: ""},
				},
			},
			{Name: "battery_string",
				Length: 1,
				Type:   types.BlockRepeating,
				Points: []types.Point{
					{Id: BatStTBD, Offset: 0, Type: typelabel.Uint16, Mandatory: true, Label: "Battery String Points To Be Determined", Description: ""},
				},
			},
		}})
}
