package model111

// Code generated by ../../generators/models.go. DO NOT EDIT.
// You can regenerate it by running 'go generate ./models' from the directory above.

import (
	"github.com/andig/gosunspec"
	"github.com/andig/gosunspec/smdx"
	"github.com/andig/gosunspec/typelabel"
)

// Block111 - Inverter (Single Phase) FLOAT - Include this model for single phase inverter monitoring using float values

const (
	ModelID          = 111
	ModelLabel       = "Inverter (Single Phase) FLOAT"
	ModelDescription = "Include this model for single phase inverter monitoring using float values"
)

const (
	A       = "A"
	AphA    = "AphA"
	AphB    = "AphB"
	AphC    = "AphC"
	DCA     = "DCA"
	DCV     = "DCV"
	DCW     = "DCW"
	Evt1    = "Evt1"
	Evt2    = "Evt2"
	EvtVnd1 = "EvtVnd1"
	EvtVnd2 = "EvtVnd2"
	EvtVnd3 = "EvtVnd3"
	EvtVnd4 = "EvtVnd4"
	Hz      = "Hz"
	PF      = "PF"
	PPVphAB = "PPVphAB"
	PPVphBC = "PPVphBC"
	PPVphCA = "PPVphCA"
	PhVphA  = "PhVphA"
	PhVphB  = "PhVphB"
	PhVphC  = "PhVphC"
	St      = "St"
	StVnd   = "StVnd"
	TmpCab  = "TmpCab"
	TmpOt   = "TmpOt"
	TmpSnk  = "TmpSnk"
	TmpTrns = "TmpTrns"
	VA      = "VA"
	VAr     = "VAr"
	W       = "W"
	WH      = "WH"
)

type Block111 struct {
	A       float32            `sunspec:"offset=0,len=2,access=r"`
	AphA    float32            `sunspec:"offset=2,len=2,access=r"`
	AphB    float32            `sunspec:"offset=4,len=2,access=r"`
	AphC    float32            `sunspec:"offset=6,len=2,access=r"`
	PPVphAB float32            `sunspec:"offset=8,len=2,access=r"`
	PPVphBC float32            `sunspec:"offset=10,len=2,access=r"`
	PPVphCA float32            `sunspec:"offset=12,len=2,access=r"`
	PhVphA  float32            `sunspec:"offset=14,len=2,access=r"`
	PhVphB  float32            `sunspec:"offset=16,len=2,access=r"`
	PhVphC  float32            `sunspec:"offset=18,len=2,access=r"`
	W       float32            `sunspec:"offset=20,len=2,access=r"`
	Hz      float32            `sunspec:"offset=22,len=2,access=r"`
	VA      float32            `sunspec:"offset=24,len=2,access=r"`
	VAr     float32            `sunspec:"offset=26,len=2,access=r"`
	PF      float32            `sunspec:"offset=28,len=2,access=r"`
	WH      float32            `sunspec:"offset=30,len=2,access=r"`
	DCA     float32            `sunspec:"offset=32,len=2,access=r"`
	DCV     float32            `sunspec:"offset=34,len=2,access=r"`
	DCW     float32            `sunspec:"offset=36,len=2,access=r"`
	TmpCab  float32            `sunspec:"offset=38,len=2,access=r"`
	TmpSnk  float32            `sunspec:"offset=40,len=2,access=r"`
	TmpTrns float32            `sunspec:"offset=42,len=2,access=r"`
	TmpOt   float32            `sunspec:"offset=44,len=2,access=r"`
	St      sunspec.Enum16     `sunspec:"offset=46,len=1,access=r"`
	StVnd   sunspec.Enum16     `sunspec:"offset=47,len=1,access=r"`
	Evt1    sunspec.Bitfield32 `sunspec:"offset=48,len=2,access=r"`
	Evt2    sunspec.Bitfield32 `sunspec:"offset=50,len=2,access=r"`
	EvtVnd1 sunspec.Bitfield32 `sunspec:"offset=52,len=2,access=r"`
	EvtVnd2 sunspec.Bitfield32 `sunspec:"offset=54,len=2,access=r"`
	EvtVnd3 sunspec.Bitfield32 `sunspec:"offset=56,len=2,access=r"`
	EvtVnd4 sunspec.Bitfield32 `sunspec:"offset=58,len=2,access=r"`
}

func (block *Block111) GetId() sunspec.ModelId {
	return ModelID
}

func init() {
	smdx.RegisterModel(&smdx.ModelElement{
		Id:     ModelID,
		Name:   "inverter",
		Length: 60,
		Blocks: []smdx.BlockElement{
			{
				Length: 60,
				Points: []smdx.PointElement{
					{Id: A, Offset: 0, Type: typelabel.Float32, Units: "A", Access: "r", Length: 2, Mandatory: true, Label: "Amps", Description: "AC Current"},
					{Id: AphA, Offset: 2, Type: typelabel.Float32, Units: "A", Access: "r", Length: 2, Mandatory: true, Label: "Amps PhaseA", Description: "Phase A Current"},
					{Id: AphB, Offset: 4, Type: typelabel.Float32, Units: "A", Access: "r", Length: 2, Label: "Amps PhaseB", Description: "Phase B Current"},
					{Id: AphC, Offset: 6, Type: typelabel.Float32, Units: "A", Access: "r", Length: 2, Label: "Amps PhaseC", Description: "Phase C Current"},
					{Id: PPVphAB, Offset: 8, Type: typelabel.Float32, Units: "V", Access: "r", Length: 2, Label: "Phase Voltage AB", Description: "Phase Voltage AB"},
					{Id: PPVphBC, Offset: 10, Type: typelabel.Float32, Units: "V", Access: "r", Length: 2, Label: "Phase Voltage BC", Description: "Phase Voltage BC"},
					{Id: PPVphCA, Offset: 12, Type: typelabel.Float32, Units: "V", Access: "r", Length: 2, Label: "Phase Voltage CA", Description: "Phase Voltage CA"},
					{Id: PhVphA, Offset: 14, Type: typelabel.Float32, Units: "V", Access: "r", Length: 2, Mandatory: true, Label: "Phase Voltage AN", Description: "Phase Voltage AN"},
					{Id: PhVphB, Offset: 16, Type: typelabel.Float32, Units: "V", Access: "r", Length: 2, Label: "Phase Voltage BN", Description: "Phase Voltage BN"},
					{Id: PhVphC, Offset: 18, Type: typelabel.Float32, Units: "V", Access: "r", Length: 2, Label: "Phase Voltage CN", Description: "Phase Voltage CN"},
					{Id: W, Offset: 20, Type: typelabel.Float32, Units: "W", Access: "r", Length: 2, Mandatory: true, Label: "Watts", Description: "AC Power"},
					{Id: Hz, Offset: 22, Type: typelabel.Float32, Units: "Hz", Access: "r", Length: 2, Mandatory: true, Label: "Hz", Description: "Line Frequency"},
					{Id: VA, Offset: 24, Type: typelabel.Float32, Units: "VA", Access: "r", Length: 2, Label: "VA", Description: "AC Apparent Power"},
					{Id: VAr, Offset: 26, Type: typelabel.Float32, Units: "var", Access: "r", Length: 2, Label: "VAr", Description: "AC Reactive Power"},
					{Id: PF, Offset: 28, Type: typelabel.Float32, Units: "Pct", Access: "r", Length: 2, Label: "PF", Description: "AC Power Factor"},
					{Id: WH, Offset: 30, Type: typelabel.Float32, Units: "Wh", Access: "r", Length: 2, Mandatory: true, Label: "WattHours", Description: "AC Energy"},
					{Id: DCA, Offset: 32, Type: typelabel.Float32, Units: "A", Access: "r", Length: 2, Label: "DC Amps", Description: "DC Current"},
					{Id: DCV, Offset: 34, Type: typelabel.Float32, Units: "V", Access: "r", Length: 2, Label: "DC Voltage", Description: "DC Voltage"},
					{Id: DCW, Offset: 36, Type: typelabel.Float32, Units: "W", Access: "r", Length: 2, Label: "DC Watts", Description: "DC Power"},
					{Id: TmpCab, Offset: 38, Type: typelabel.Float32, Units: "C", Access: "r", Length: 2, Mandatory: true, Label: "Cabinet Temperature", Description: "Cabinet Temperature"},
					{Id: TmpSnk, Offset: 40, Type: typelabel.Float32, Units: "C", Access: "r", Length: 2, Label: "Heat Sink Temperature", Description: "Heat Sink Temperature"},
					{Id: TmpTrns, Offset: 42, Type: typelabel.Float32, Units: "C", Access: "r", Length: 2, Label: "Transformer Temperature", Description: "Transformer Temperature"},
					{Id: TmpOt, Offset: 44, Type: typelabel.Float32, Units: "C", Access: "r", Length: 2, Label: "Other Temperature", Description: "Other Temperature"},
					{Id: St, Offset: 46, Type: typelabel.Enum16, Access: "r", Length: 1, Mandatory: true, Label: "Operating State", Description: "Enumerated value.  Operating state"},
					{Id: StVnd, Offset: 47, Type: typelabel.Enum16, Access: "r", Length: 1, Label: "Vendor Operating State", Description: "Vendor specific operating state code"},
					{Id: Evt1, Offset: 48, Type: typelabel.Bitfield32, Access: "r", Length: 2, Mandatory: true, Label: "Event1", Description: "Bitmask value. Event fields"},
					{Id: Evt2, Offset: 50, Type: typelabel.Bitfield32, Access: "r", Length: 2, Mandatory: true, Label: "Event Bitfield 2", Description: "Reserved for future use"},
					{Id: EvtVnd1, Offset: 52, Type: typelabel.Bitfield32, Access: "r", Length: 2, Label: "Vendor Event Bitfield 1", Description: "Vendor defined events"},
					{Id: EvtVnd2, Offset: 54, Type: typelabel.Bitfield32, Access: "r", Length: 2, Label: "Vendor Event Bitfield 2", Description: "Vendor defined events"},
					{Id: EvtVnd3, Offset: 56, Type: typelabel.Bitfield32, Access: "r", Length: 2, Label: "Vendor Event Bitfield 3", Description: "Vendor defined events"},
					{Id: EvtVnd4, Offset: 58, Type: typelabel.Bitfield32, Access: "r", Length: 2, Label: "Vendor Event Bitfield 4", Description: "Vendor defined events"},
				},
			},
		}})
}
