package model64412

// Code generated by ../../generators/json/models.go. DO NOT EDIT.
// You can regenerate it by running 'make spec' from the project root.

import (
	"github.com/andig/gosunspec"
	"github.com/andig/gosunspec/typelabel"
	"github.com/andig/gosunspec/types"
)

// Block64412 - DER Cyber Exploitation - Operations that represent a hacked DER device

const (
	ModelID          = 64412
	ModelLabel       = "DER Cyber Exploitation"
	ModelDescription = "Operations that represent a hacked DER device"
)

const (
	ChangeCommonModelID     = "ChangeCommonModelID"
	ChangeCommonModelLength = "ChangeCommonModelLength"
	DAManipulation          = "DAManipulation"
	FalsifyDeviceIdentity   = "FalsifyDeviceIdentity"
	MeasHighAmps            = "MeasHighAmps"
	MeasHighF               = "MeasHighF"
	MeasHighL1V             = "MeasHighL1V"
	MeasHighQ               = "MeasHighQ"
	MeasHighS               = "MeasHighS"
	MeasHighV               = "MeasHighV"
	MeasInvertQ             = "MeasInvertQ"
	MeasLowAmps             = "MeasLowAmps"
	MeasLowF                = "MeasLowF"
	MeasLowL1V              = "MeasLowL1V"
	MeasLowPF               = "MeasLowPF"
	MeasLowQ                = "MeasLowQ"
	MeasLowReversedPF       = "MeasLowReversedPF"
	MeasLowS                = "MeasLowS"
	MeasLowV                = "MeasLowV"
	MeasPAlwaysNameplate    = "MeasPAlwaysNameplate"
	MeasQAlwaysMaximum      = "MeasQAlwaysMaximum"
	MeasQAlwaysMinimum      = "MeasQAlwaysMinimum"
	MeasQAlwaysZero         = "MeasQAlwaysZero"
	MeasZeroP               = "MeasZeroP"
	NameplateHighNomV       = "NameplateHighNomV"
	NameplateHighP          = "NameplateHighP"
	NameplateHighQ          = "NameplateHighQ"
	NameplateHighS          = "NameplateHighS"
	NameplateLowAmps        = "NameplateLowAmps"
	NameplateLowNomV        = "NameplateLowNomV"
	NameplateLowP           = "NameplateLowP"
	NameplateLowPF          = "NameplateLowPF"
	NameplateLowQ           = "NameplateLowQ"
	NameplateLowS           = "NameplateLowS"
	NameplateLowVarmaxabs   = "NameplateLowVarmaxabs"
	NameplateLowVarmaxinj   = "NameplateLowVarmaxinj"
	SettingsHighNomV        = "SettingsHighNomV"
	SettingsHighP           = "SettingsHighP"
	SettingsHighVAMax       = "SettingsHighVAMax"
	SettingsHighVarmaxabs   = "SettingsHighVarmaxabs"
	SettingsHighVarmaxinj   = "SettingsHighVarmaxinj"
	SettingsLowAmps         = "SettingsLowAmps"
	SettingsLowP            = "SettingsLowP"
)

type Block64412 struct {
	DAManipulation          sunspec.Enum16 `sunspec:"offset=0,access=rw"`
	FalsifyDeviceIdentity   sunspec.Enum16 `sunspec:"offset=1,access=rw"`
	MeasPAlwaysNameplate    sunspec.Enum16 `sunspec:"offset=2,access=rw"`
	MeasQAlwaysMinimum      sunspec.Enum16 `sunspec:"offset=3,access=rw"`
	MeasQAlwaysMaximum      sunspec.Enum16 `sunspec:"offset=4,access=rw"`
	MeasQAlwaysZero         sunspec.Enum16 `sunspec:"offset=5,access=rw"`
	MeasZeroP               sunspec.Enum16 `sunspec:"offset=6,access=rw"`
	MeasInvertQ             sunspec.Enum16 `sunspec:"offset=7,access=rw"`
	MeasLowV                sunspec.Enum16 `sunspec:"offset=8,access=rw"`
	MeasHighV               sunspec.Enum16 `sunspec:"offset=9,access=rw"`
	MeasLowL1V              sunspec.Enum16 `sunspec:"offset=10,access=rw"`
	MeasHighL1V             sunspec.Enum16 `sunspec:"offset=11,access=rw"`
	MeasLowF                sunspec.Enum16 `sunspec:"offset=12,access=rw"`
	MeasHighF               sunspec.Enum16 `sunspec:"offset=13,access=rw"`
	MeasLowAmps             sunspec.Enum16 `sunspec:"offset=14,access=rw"`
	MeasHighAmps            sunspec.Enum16 `sunspec:"offset=15,access=rw"`
	MeasHighS               sunspec.Enum16 `sunspec:"offset=16,access=rw"`
	MeasLowS                sunspec.Enum16 `sunspec:"offset=17,access=rw"`
	MeasHighQ               sunspec.Enum16 `sunspec:"offset=18,access=rw"`
	MeasLowQ                sunspec.Enum16 `sunspec:"offset=19,access=rw"`
	MeasLowPF               sunspec.Enum16 `sunspec:"offset=20,access=rw"`
	MeasLowReversedPF       sunspec.Enum16 `sunspec:"offset=21,access=rw"`
	NameplateHighP          sunspec.Enum16 `sunspec:"offset=22,access=rw"`
	NameplateLowP           sunspec.Enum16 `sunspec:"offset=23,access=rw"`
	NameplateHighS          sunspec.Enum16 `sunspec:"offset=24,access=rw"`
	NameplateLowS           sunspec.Enum16 `sunspec:"offset=25,access=rw"`
	NameplateHighQ          sunspec.Enum16 `sunspec:"offset=26,access=rw"`
	NameplateLowQ           sunspec.Enum16 `sunspec:"offset=27,access=rw"`
	NameplateHighNomV       sunspec.Enum16 `sunspec:"offset=28,access=rw"`
	NameplateLowNomV        sunspec.Enum16 `sunspec:"offset=29,access=rw"`
	NameplateLowAmps        sunspec.Enum16 `sunspec:"offset=30,access=rw"`
	NameplateLowVarmaxinj   sunspec.Enum16 `sunspec:"offset=31,access=rw"`
	NameplateLowVarmaxabs   sunspec.Enum16 `sunspec:"offset=32,access=rw"`
	NameplateLowPF          sunspec.Enum16 `sunspec:"offset=33,access=rw"`
	SettingsHighNomV        sunspec.Enum16 `sunspec:"offset=34,access=rw"`
	SettingsLowAmps         sunspec.Enum16 `sunspec:"offset=35,access=rw"`
	SettingsHighP           sunspec.Enum16 `sunspec:"offset=36,access=rw"`
	SettingsLowP            sunspec.Enum16 `sunspec:"offset=37,access=rw"`
	SettingsHighVAMax       sunspec.Enum16 `sunspec:"offset=38,access=rw"`
	SettingsHighVarmaxinj   sunspec.Enum16 `sunspec:"offset=39,access=rw"`
	SettingsHighVarmaxabs   sunspec.Enum16 `sunspec:"offset=40,access=rw"`
	ChangeCommonModelID     sunspec.Enum16 `sunspec:"offset=41,access=rw"`
	ChangeCommonModelLength sunspec.Enum16 `sunspec:"offset=42,access=rw"`
}

func (block *Block64412) GetId() sunspec.ModelId {
	return ModelID
}

func init() {
	types.RegisterModel(&types.Model{
		Id:          ModelID,
		Name:        "DERExploitation",
		Label:       "DER Cyber Exploitation",
		Description: "Operations that represent a hacked DER device",
		Length:      43,
		Blocks: []types.Block{
			{
				Length: 43,
				Type:   types.BlockFixed,
				Points: []types.Point{
					{Id: DAManipulation, Offset: 0, Type: typelabel.Enum16, Access: "rw", Label: "DA Manipulation", Description: "Modify the device ID of the DER"},
					{Id: FalsifyDeviceIdentity, Offset: 1, Type: typelabel.Enum16, Access: "rw", Label: "Falsify Device Identity", Description: "Change the DER manufacturer and model"},
					{Id: MeasPAlwaysNameplate, Offset: 2, Type: typelabel.Enum16, Access: "rw", Label: "Meas P Always Nameplate", Description: "Set the DER meas to always be at nameplate power"},
					{Id: MeasQAlwaysMinimum, Offset: 3, Type: typelabel.Enum16, Access: "rw", Label: "Meas Q Always Minimum", Description: "Set the DER to always be at minimum reactive power"},
					{Id: MeasQAlwaysMaximum, Offset: 4, Type: typelabel.Enum16, Access: "rw", Label: "Meas Q Always Maximum", Description: "Set the DER to always be at maximum reactive power"},
					{Id: MeasQAlwaysZero, Offset: 5, Type: typelabel.Enum16, Access: "rw", Label: "Meas Q Always Zero", Description: "Set the DER to always be at zero reactive power"},
					{Id: MeasZeroP, Offset: 6, Type: typelabel.Enum16, Access: "rw", Label: "Meas Zero P", Description: "Set the DER to always be at zero P, Q, and S"},
					{Id: MeasInvertQ, Offset: 7, Type: typelabel.Enum16, Access: "rw", Label: "Meas Invert Q", Description: "Set the DER to reverse the Q measurement data"},
					{Id: MeasLowV, Offset: 8, Type: typelabel.Enum16, Access: "rw", Label: "Meas Low V", Description: "Set the DER to always measure low voltage"},
					{Id: MeasHighV, Offset: 9, Type: typelabel.Enum16, Access: "rw", Label: "Meas High V", Description: "Set the DER to always measure high voltage"},
					{Id: MeasLowL1V, Offset: 10, Type: typelabel.Enum16, Access: "rw", Label: "Meas Low L1 V", Description: "Set the DER to always measure low line 1 voltage"},
					{Id: MeasHighL1V, Offset: 11, Type: typelabel.Enum16, Access: "rw", Label: "Meas High L1 V", Description: "Set the DER to always measure high line 1 voltage"},
					{Id: MeasLowF, Offset: 12, Type: typelabel.Enum16, Access: "rw", Label: "Meas Low F", Description: "Set the DER to always measure low frequency"},
					{Id: MeasHighF, Offset: 13, Type: typelabel.Enum16, Access: "rw", Label: "Meas High F", Description: "Set the DER to always measure high frequency"},
					{Id: MeasLowAmps, Offset: 14, Type: typelabel.Enum16, Access: "rw", Label: "Meas Low Amps", Description: "Set the DER to always measure low current"},
					{Id: MeasHighAmps, Offset: 15, Type: typelabel.Enum16, Access: "rw", Label: "Meas High Amps", Description: "Set the DER to always measure high current"},
					{Id: MeasHighS, Offset: 16, Type: typelabel.Enum16, Access: "rw", Label: "Meas High S", Description: "Set the DER to always measure high apparent power"},
					{Id: MeasLowS, Offset: 17, Type: typelabel.Enum16, Access: "rw", Label: "Meas Low S", Description: "Set the DER to always measure low apparent power"},
					{Id: MeasHighQ, Offset: 18, Type: typelabel.Enum16, Access: "rw", Label: "Meas High Q", Description: "Set the DER to always measure high reactive power"},
					{Id: MeasLowQ, Offset: 19, Type: typelabel.Enum16, Access: "rw", Label: "Meas Low Q", Description: "Set the DER to always measure low reactive power"},
					{Id: MeasLowPF, Offset: 20, Type: typelabel.Enum16, Access: "rw", Label: "Meas Low PF", Description: "Set the DER to always measure low power factor"},
					{Id: MeasLowReversedPF, Offset: 21, Type: typelabel.Enum16, Access: "rw", Label: "Meas Low Reversed PF", Description: "Set the DER to always measure low reversed power factor"},
					{Id: NameplateHighP, Offset: 22, Type: typelabel.Enum16, Access: "rw", Label: "Nameplate High P", Description: "Set the DER nameplate power to be high"},
					{Id: NameplateLowP, Offset: 23, Type: typelabel.Enum16, Access: "rw", Label: "Nameplate Low P", Description: "Set the DER nameplate power to be low"},
					{Id: NameplateHighS, Offset: 24, Type: typelabel.Enum16, Access: "rw", Label: "Nameplate High S", Description: "Set the DER nameplate apparent power to be high"},
					{Id: NameplateLowS, Offset: 25, Type: typelabel.Enum16, Access: "rw", Label: "Nameplate Low S", Description: "Set the DER nameplate apparent power to be low"},
					{Id: NameplateHighQ, Offset: 26, Type: typelabel.Enum16, Access: "rw", Label: "Nameplate High Q", Description: "Set the DER nameplate reactive power to be high"},
					{Id: NameplateLowQ, Offset: 27, Type: typelabel.Enum16, Access: "rw", Label: "Nameplate Low Q", Description: "Set the DER nameplate reactive power to be low"},
					{Id: NameplateHighNomV, Offset: 28, Type: typelabel.Enum16, Access: "rw", Label: "Nameplate High Nom V", Description: "Set the DER nameplate voltage to be high"},
					{Id: NameplateLowNomV, Offset: 29, Type: typelabel.Enum16, Access: "rw", Label: "Nameplate Low Nom V", Description: "Set the DER nameplate voltage to be low"},
					{Id: NameplateLowAmps, Offset: 30, Type: typelabel.Enum16, Access: "rw", Label: "Nameplate Low Amps", Description: "Set the DER nameplate current to be low"},
					{Id: NameplateLowVarmaxinj, Offset: 31, Type: typelabel.Enum16, Access: "rw", Label: "Nameplate Low Varmaxinj", Description: "Set the DER nameplate VarMaxInj to be low"},
					{Id: NameplateLowVarmaxabs, Offset: 32, Type: typelabel.Enum16, Access: "rw", Label: "Nameplate Low Varmaxabs", Description: "Set the DER nameplate VarMaxAbs to be low"},
					{Id: NameplateLowPF, Offset: 33, Type: typelabel.Enum16, Access: "rw", Label: "Nameplate Low PF", Description: "Set the DER nameplate power factor to be low"},
					{Id: SettingsHighNomV, Offset: 34, Type: typelabel.Enum16, Access: "rw", Label: "Settings High Nom V", Description: "Set the DER settings voltage to be high"},
					{Id: SettingsLowAmps, Offset: 35, Type: typelabel.Enum16, Access: "rw", Label: "Settings Low Amps", Description: "Set the DER settings current to be low"},
					{Id: SettingsHighP, Offset: 36, Type: typelabel.Enum16, Access: "rw", Label: "Settings High P", Description: "Set the DER settings power to be high"},
					{Id: SettingsLowP, Offset: 37, Type: typelabel.Enum16, Access: "rw", Label: "Settings Low P", Description: "Set the DER settings power to be low"},
					{Id: SettingsHighVAMax, Offset: 38, Type: typelabel.Enum16, Access: "rw", Label: "Settings High VAMax", Description: "Set the DER settings VAMax to be high"},
					{Id: SettingsHighVarmaxinj, Offset: 39, Type: typelabel.Enum16, Access: "rw", Label: "Settings High Varmaxinj", Description: "Set the DER settings VarMaxInj to be high"},
					{Id: SettingsHighVarmaxabs, Offset: 40, Type: typelabel.Enum16, Access: "rw", Label: "Settings High Varmaxabs", Description: "Set the DER settings VarMaxAbs to be high"},
					{Id: ChangeCommonModelID, Offset: 41, Type: typelabel.Enum16, Access: "rw", Label: "Change Common Model ID", Description: "Change the common model ID"},
					{Id: ChangeCommonModelLength, Offset: 42, Type: typelabel.Enum16, Access: "rw", Label: "Change Common Model Length", Description: "Change the common model length"},
				},
			},
		}})
}
