package model710

// Code generated by ../../generators/json/models.go. DO NOT EDIT.
// You can regenerate it by running 'make spec' from the project root.

import (
	"github.com/andig/gosunspec"
	"github.com/andig/gosunspec/typelabel"
	"github.com/andig/gosunspec/types"
)

// Block710 - DER Trip HF - DER high frequency trip model.

const (
	ModelID          = 710
	ModelLabel       = "DER Trip HF"
	ModelDescription = "DER high frequency trip model."
)

const (
	ActPt       = "ActPt"
	AdptCrvReq  = "AdptCrvReq"
	AdptCrvRslt = "AdptCrvRslt"
	Ena         = "Ena"
	Hz          = "Hz"
	Hz_SF       = "Hz_SF"
	NCrvSet     = "NCrvSet"
	NPt         = "NPt"
	ReadOnly    = "ReadOnly"
	Tms         = "Tms"
	Tms_SF      = "Tms_SF"
)

type Block710CrvRepeat struct {
	ReadOnly sunspec.Enum16 `sunspec:"offset=0"`
}

type Block710MustTripRepeat struct {
	ActPt uint16 `sunspec:"offset=0,access=rw"`
}

type Block710PtRepeat struct {
	Hz  uint32 `sunspec:"offset=0,sf=Hz_SF,access=rw"`
	Tms uint32 `sunspec:"offset=2,sf=Tms_SF,access=rw"`
}

type Block710MayTripRepeat struct {
	ActPt uint16 `sunspec:"offset=0,access=rw"`
}

type Block710Pt_2Repeat struct {
	Hz  uint32 `sunspec:"offset=0,sf=Hz_SF,access=rw"`
	Tms uint32 `sunspec:"offset=2,sf=Tms_SF,access=rw"`
}

type Block710MomCessRepeat struct {
	ActPt uint16 `sunspec:"offset=0,access=rw"`
}

type Block710Pt_3Repeat struct {
	Hz  uint32 `sunspec:"offset=0,sf=Hz_SF,access=rw"`
	Tms uint32 `sunspec:"offset=2,sf=Tms_SF,access=rw"`
}

type Block710 struct {
	Ena         sunspec.Enum16      `sunspec:"offset=0,access=rw"`
	AdptCrvReq  uint16              `sunspec:"offset=1,access=rw"`
	AdptCrvRslt sunspec.Enum16      `sunspec:"offset=2"`
	NPt         uint16              `sunspec:"offset=3"`
	NCrvSet     uint16              `sunspec:"offset=4"`
	Hz_SF       sunspec.ScaleFactor `sunspec:"offset=5"`
	Tms_SF      sunspec.ScaleFactor `sunspec:"offset=6"`

	Crv []Block710CrvRepeat

	MustTrip []Block710MustTripRepeat

	Pt []Block710PtRepeat

	MayTrip []Block710MayTripRepeat

	Pt_2 []Block710Pt_2Repeat

	MomCess []Block710MomCessRepeat

	Pt_3 []Block710Pt_3Repeat
}

func (block *Block710) GetId() sunspec.ModelId {
	return ModelID
}

func init() {
	types.RegisterModel(&types.Model{
		Id:          ModelID,
		Name:        "DERTripHF",
		Label:       "DER Trip HF",
		Description: "DER high frequency trip model.",
		Length:      23,
		Blocks: []types.Block{
			{
				Length: 7,
				Type:   types.BlockFixed,
				Points: []types.Point{
					{Id: Ena, Offset: 0, Type: typelabel.Enum16, Access: "rw", Mandatory: true, Label: "DER Trip HF Module Enable", Description: "DER high frequency trip control enable."},
					{Id: AdptCrvReq, Offset: 1, Type: typelabel.Uint16, Access: "rw", Mandatory: true, Label: "Adopt Curve Request", Description: "Index of curve points to adopt. First curve index is 1."},
					{Id: AdptCrvRslt, Offset: 2, Type: typelabel.Enum16, Mandatory: true, Label: "Adopt Curve Result", Description: "Result of last adopt curve operation."},
					{Id: NPt, Offset: 3, Type: typelabel.Uint16, Mandatory: true, Label: "Number Of Points", Description: "Number of curve points supported."},
					{Id: NCrvSet, Offset: 4, Type: typelabel.Uint16, Mandatory: true, Label: "Stored Curve Count", Description: "Number of stored curves supported."},
					{Id: Hz_SF, Offset: 5, Type: typelabel.ScaleFactor, Mandatory: true, Label: "Frequency Scale Factor", Description: "Scale factor for curve frequency points."},
					{Id: Tms_SF, Offset: 6, Type: typelabel.ScaleFactor, Mandatory: true, Label: "Time Point Scale Factor", Description: "Scale factor for curve time points."},
				},
			},
			{Name: "Crv",
				Length: 1,
				Type:   types.BlockRepeating,
				Points: []types.Point{
					{Id: ReadOnly, Offset: 0, Type: typelabel.Enum16, Mandatory: true, Label: "Curve Access", Description: "Curve read-write access."},
				},
			},
			{Name: "MustTrip",
				Length: 1,
				Type:   types.BlockRepeating,
				Points: []types.Point{
					{Id: ActPt, Offset: 0, Type: typelabel.Uint16, Access: "rw", Label: "Number Of Active Points", Description: "Number of active points in must trip curve."},
				},
			},
			{Name: "Pt",
				Length: 4,
				Type:   types.BlockRepeating,
				Points: []types.Point{
					{Id: Hz, Offset: 0, Type: typelabel.Uint32, ScaleFactor: "Hz_SF", Units: "Hz", Access: "rw", Label: "Frequency Point", Description: "Curve frequency point."},
					{Id: Tms, Offset: 2, Type: typelabel.Uint32, ScaleFactor: "Tms_SF", Units: "Secs", Access: "rw", Label: "Time Point", Description: "Curve time point in seconds."},
				},
			},
			{Name: "MayTrip",
				Length: 1,
				Type:   types.BlockRepeating,
				Points: []types.Point{
					{Id: ActPt, Offset: 0, Type: typelabel.Uint16, Access: "rw", Label: "Number Of Active Points", Description: "Number of active points in may trip curve."},
				},
			},
			{Name: "Pt_2",
				Length: 4,
				Type:   types.BlockRepeating,
				Points: []types.Point{
					{Id: Hz, Offset: 0, Type: typelabel.Uint32, ScaleFactor: "Hz_SF", Units: "Hz", Access: "rw", Label: "Frequency Point", Description: "Curve frequency point."},
					{Id: Tms, Offset: 2, Type: typelabel.Uint32, ScaleFactor: "Tms_SF", Units: "Secs", Access: "rw", Label: "Time Point", Description: "Curve time point in seconds."},
				},
			},
			{Name: "MomCess",
				Length: 1,
				Type:   types.BlockRepeating,
				Points: []types.Point{
					{Id: ActPt, Offset: 0, Type: typelabel.Uint16, Access: "rw", Label: "Number Of Active Points", Description: "Number of active points in the momentary cessation curve."},
				},
			},
			{Name: "Pt_3",
				Length: 4,
				Type:   types.BlockRepeating,
				Points: []types.Point{
					{Id: Hz, Offset: 0, Type: typelabel.Uint32, ScaleFactor: "Hz_SF", Units: "Hz", Access: "rw", Label: "Frequency Point", Description: "Curve frequency point."},
					{Id: Tms, Offset: 2, Type: typelabel.Uint32, ScaleFactor: "Tms_SF", Units: "Secs", Access: "rw", Label: "Time Point", Description: "Curve time point in seconds."},
				},
			},
		}})
}
