package model703

// Code generated by ../../generators/json/models.go. DO NOT EDIT.
// You can regenerate it by running 'make spec' from the project root.

import (
	"github.com/andig/gosunspec"
	"github.com/andig/gosunspec/typelabel"
	"github.com/andig/gosunspec/types"
)

// Block703 - Enter Service - Enter service model.

const (
	ModelID          = 703
	ModelLabel       = "Enter Service"
	ModelDescription = "Enter service model."
)

const (
	ES          = "ES"
	ESDlyRemTms = "ESDlyRemTms"
	ESDlyTms    = "ESDlyTms"
	ESHzHi      = "ESHzHi"
	ESHzLo      = "ESHzLo"
	ESRmpTms    = "ESRmpTms"
	ESRndTms    = "ESRndTms"
	ESVHi       = "ESVHi"
	ESVLo       = "ESVLo"
	Hz_SF       = "Hz_SF"
	V_SF        = "V_SF"
)

type Block703 struct {
	ES          sunspec.Enum16      `sunspec:"offset=0,access=rw"`
	ESVHi       uint16              `sunspec:"offset=1,sf=V_SF,access=rw"`
	ESVLo       uint16              `sunspec:"offset=2,sf=V_SF,access=rw"`
	ESHzHi      uint32              `sunspec:"offset=3,sf=Hz_SF,access=rw"`
	ESHzLo      uint32              `sunspec:"offset=5,sf=Hz_SF,access=rw"`
	ESDlyTms    uint32              `sunspec:"offset=7,access=rw"`
	ESRndTms    uint32              `sunspec:"offset=9,access=rw"`
	ESRmpTms    uint32              `sunspec:"offset=11,access=rw"`
	ESDlyRemTms uint32              `sunspec:"offset=13"`
	V_SF        sunspec.ScaleFactor `sunspec:"offset=15"`
	Hz_SF       sunspec.ScaleFactor `sunspec:"offset=16"`
}

func (block *Block703) GetId() sunspec.ModelId {
	return ModelID
}

func init() {
	types.RegisterModel(&types.Model{
		Id:          ModelID,
		Name:        "DEREnterService",
		Label:       "Enter Service",
		Description: "Enter service model.",
		Length:      17,
		Blocks: []types.Block{
			{
				Length: 17,
				Type:   types.BlockFixed,
				Points: []types.Point{
					{Id: ES, Offset: 0, Type: typelabel.Enum16, Access: "rw", Label: "Permit Enter Service", Description: "Permit enter service."},
					{Id: ESVHi, Offset: 1, Type: typelabel.Uint16, ScaleFactor: "V_SF", Units: "Pct", Access: "rw", Label: "Enter Service Voltage High", Description: "Enter service voltage high threshold as percent of normal voltage."},
					{Id: ESVLo, Offset: 2, Type: typelabel.Uint16, ScaleFactor: "V_SF", Units: "Pct", Access: "rw", Label: "Enter Service Voltage Low", Description: "Enter service voltage low threshold as percent of normal voltage."},
					{Id: ESHzHi, Offset: 3, Type: typelabel.Uint32, ScaleFactor: "Hz_SF", Units: "Hz", Access: "rw", Label: "Enter Service Frequency High", Description: "Enter service frequency high threshold."},
					{Id: ESHzLo, Offset: 5, Type: typelabel.Uint32, ScaleFactor: "Hz_SF", Units: "Hz", Access: "rw", Label: "Enter Service Frequency Low", Description: "Enter service frequency low threshold."},
					{Id: ESDlyTms, Offset: 7, Type: typelabel.Uint32, Units: "Secs", Access: "rw", Label: "Enter Service Delay Time", Description: "Enter service delay time in seconds."},
					{Id: ESRndTms, Offset: 9, Type: typelabel.Uint32, Units: "Secs", Access: "rw", Label: "Enter Service Random Delay", Description: "Enter service random delay in seconds."},
					{Id: ESRmpTms, Offset: 11, Type: typelabel.Uint32, Units: "Secs", Access: "rw", Label: "Enter Service Ramp Time", Description: "Enter service ramp time in seconds."},
					{Id: ESDlyRemTms, Offset: 13, Type: typelabel.Uint32, Units: "Secs", Label: "Enter Service Delay Remaining", Description: "Enter service delay time remaining in seconds."},
					{Id: V_SF, Offset: 15, Type: typelabel.ScaleFactor, Label: "Voltage Scale Factor", Description: "Voltage percentage scale factor."},
					{Id: Hz_SF, Offset: 16, Type: typelabel.ScaleFactor, Label: "Frequency Scale Factor", Description: "Frequency scale factor."},
				},
			},
		}})
}
