package model702

// Code generated by ../../generators/json/models.go. DO NOT EDIT.
// You can regenerate it by running 'make spec' from the project root.

import (
	"github.com/andig/gosunspec"
	"github.com/andig/gosunspec/typelabel"
	"github.com/andig/gosunspec/types"
)

// Block702 - DER Capacity - DER capacity model.

const (
	ModelID          = 702
	ModelLabel       = "DER Capacity"
	ModelDescription = "DER capacity model."
)

const (
	AMax              = "AMax"
	AMaxRtg           = "AMaxRtg"
	A_SF              = "A_SF"
	AbnOpCatRtg       = "AbnOpCatRtg"
	CtrlModes         = "CtrlModes"
	IntIslandCat      = "IntIslandCat"
	IntIslandCatRtg   = "IntIslandCatRtg"
	NorOpCatRtg       = "NorOpCatRtg"
	PFOvrExt          = "PFOvrExt"
	PFOvrExtRtg       = "PFOvrExtRtg"
	PFUndExt          = "PFUndExt"
	PFUndExtRtg       = "PFUndExtRtg"
	PF_SF             = "PF_SF"
	ReactSusceptRtg   = "ReactSusceptRtg"
	S_SF              = "S_SF"
	VAChaRteMax       = "VAChaRteMax"
	VAChaRteMaxRtg    = "VAChaRteMaxRtg"
	VADisChaRteMax    = "VADisChaRteMax"
	VADisChaRteMaxRtg = "VADisChaRteMaxRtg"
	VAMax             = "VAMax"
	VAMaxRtg          = "VAMaxRtg"
	VA_SF             = "VA_SF"
	VMax              = "VMax"
	VMaxRtg           = "VMaxRtg"
	VMin              = "VMin"
	VMinRtg           = "VMinRtg"
	VNom              = "VNom"
	VNomRtg           = "VNomRtg"
	V_SF              = "V_SF"
	VarMaxAbs         = "VarMaxAbs"
	VarMaxAbsRtg      = "VarMaxAbsRtg"
	VarMaxInj         = "VarMaxInj"
	VarMaxInjRtg      = "VarMaxInjRtg"
	Var_SF            = "Var_SF"
	WChaRteMax        = "WChaRteMax"
	WChaRteMaxRtg     = "WChaRteMaxRtg"
	WDisChaRteMax     = "WDisChaRteMax"
	WDisChaRteMaxRtg  = "WDisChaRteMaxRtg"
	WMax              = "WMax"
	WMaxOvrExt        = "WMaxOvrExt"
	WMaxRtg           = "WMaxRtg"
	WMaxUndExt        = "WMaxUndExt"
	WOvrExtPF         = "WOvrExtPF"
	WOvrExtRtg        = "WOvrExtRtg"
	WOvrExtRtgPF      = "WOvrExtRtgPF"
	WUndExtPF         = "WUndExtPF"
	WUndExtRtg        = "WUndExtRtg"
	WUndExtRtgPF      = "WUndExtRtgPF"
	W_SF              = "W_SF"
)

type Block702 struct {
	WMaxRtg           uint16              `sunspec:"offset=0,sf=W_SF"`
	WOvrExtRtg        uint16              `sunspec:"offset=1,sf=W_SF"`
	WOvrExtRtgPF      uint16              `sunspec:"offset=2,sf=PF_SF"`
	WUndExtRtg        uint16              `sunspec:"offset=3,sf=W_SF"`
	WUndExtRtgPF      uint16              `sunspec:"offset=4,sf=PF_SF"`
	VAMaxRtg          uint16              `sunspec:"offset=5,sf=VA_SF"`
	VarMaxInjRtg      uint16              `sunspec:"offset=6,sf=Var_SF"`
	VarMaxAbsRtg      uint16              `sunspec:"offset=7,sf=Var_SF"`
	WChaRteMaxRtg     uint16              `sunspec:"offset=8,sf=W_SF"`
	WDisChaRteMaxRtg  uint16              `sunspec:"offset=9,sf=W_SF"`
	VAChaRteMaxRtg    uint16              `sunspec:"offset=10,sf=VA_SF"`
	VADisChaRteMaxRtg uint16              `sunspec:"offset=11,sf=VA_SF"`
	VNomRtg           uint16              `sunspec:"offset=12,sf=V_SF"`
	VMaxRtg           uint16              `sunspec:"offset=13,sf=V_SF"`
	VMinRtg           uint16              `sunspec:"offset=14,sf=V_SF"`
	AMaxRtg           uint16              `sunspec:"offset=15,sf=A_SF"`
	PFOvrExtRtg       uint16              `sunspec:"offset=16,sf=PF_SF"`
	PFUndExtRtg       uint16              `sunspec:"offset=17,sf=PF_SF"`
	ReactSusceptRtg   uint16              `sunspec:"offset=18,sf=S_SF"`
	NorOpCatRtg       sunspec.Enum16      `sunspec:"offset=19"`
	AbnOpCatRtg       sunspec.Enum16      `sunspec:"offset=20"`
	CtrlModes         sunspec.Bitfield32  `sunspec:"offset=21"`
	IntIslandCatRtg   sunspec.Bitfield16  `sunspec:"offset=23"`
	WMax              uint16              `sunspec:"offset=24,sf=W_SF,access=rw"`
	WMaxOvrExt        uint16              `sunspec:"offset=25,sf=W_SF,access=rw"`
	WOvrExtPF         uint16              `sunspec:"offset=26,sf=PF_SF,access=rw"`
	WMaxUndExt        uint16              `sunspec:"offset=27,sf=W_SF,access=rw"`
	WUndExtPF         uint16              `sunspec:"offset=28,sf=PF_SF,access=rw"`
	VAMax             uint16              `sunspec:"offset=29,sf=VA_SF,access=rw"`
	VarMaxInj         uint16              `sunspec:"offset=30,sf=Var_SF,access=rw"`
	VarMaxAbs         uint16              `sunspec:"offset=31,sf=Var_SF,access=rw"`
	WChaRteMax        uint16              `sunspec:"offset=32,sf=W_SF,access=rw"`
	WDisChaRteMax     uint16              `sunspec:"offset=33,sf=W_SF,access=rw"`
	VAChaRteMax       uint16              `sunspec:"offset=34,sf=VA_SF,access=rw"`
	VADisChaRteMax    uint16              `sunspec:"offset=35,sf=VA_SF,access=rw"`
	VNom              uint16              `sunspec:"offset=36,sf=V_SF,access=rw"`
	VMax              uint16              `sunspec:"offset=37,sf=V_SF,access=rw"`
	VMin              uint16              `sunspec:"offset=38,sf=V_SF,access=rw"`
	AMax              uint16              `sunspec:"offset=39,sf=A_SF,access=rw"`
	PFOvrExt          uint16              `sunspec:"offset=40,sf=PF_SF,access=rw"`
	PFUndExt          uint16              `sunspec:"offset=41,sf=PF_SF,access=rw"`
	IntIslandCat      sunspec.Bitfield16  `sunspec:"offset=42,access=rw"`
	W_SF              sunspec.ScaleFactor `sunspec:"offset=43"`
	PF_SF             sunspec.ScaleFactor `sunspec:"offset=44"`
	VA_SF             sunspec.ScaleFactor `sunspec:"offset=45"`
	Var_SF            sunspec.ScaleFactor `sunspec:"offset=46"`
	V_SF              sunspec.ScaleFactor `sunspec:"offset=47"`
	A_SF              sunspec.ScaleFactor `sunspec:"offset=48"`
	S_SF              sunspec.ScaleFactor `sunspec:"offset=49"`
}

func (block *Block702) GetId() sunspec.ModelId {
	return ModelID
}

func init() {
	types.RegisterModel(&types.Model{
		Id:          ModelID,
		Name:        "DERCapacity",
		Label:       "DER Capacity",
		Description: "DER capacity model.",
		Length:      50,
		Blocks: []types.Block{
			{
				Length: 50,
				Type:   types.BlockFixed,
				Points: []types.Point{
					{Id: WMaxRtg, Offset: 0, Type: typelabel.Uint16, ScaleFactor: "W_SF", Units: "W", Label: "Active Power Max Rating", Description: "Maximum active power rating at unity power factor in watts."},
					{Id: WOvrExtRtg, Offset: 1, Type: typelabel.Uint16, ScaleFactor: "W_SF", Units: "W", Label: "Active Power (Over-Excited) Rating", Description: "Active power rating at specified over-excited power factor in watts."},
					{Id: WOvrExtRtgPF, Offset: 2, Type: typelabel.Uint16, ScaleFactor: "PF_SF", Label: "Specified Over-Excited PF", Description: "Specified over-excited power factor."},
					{Id: WUndExtRtg, Offset: 3, Type: typelabel.Uint16, ScaleFactor: "W_SF", Units: "W", Label: "Active Power (Under-Excited) Rating", Description: "Active power rating at specified under-excited power factor in watts."},
					{Id: WUndExtRtgPF, Offset: 4, Type: typelabel.Uint16, ScaleFactor: "PF_SF", Label: "Specified Under-Excited PF", Description: "Specified under-excited power factor."},
					{Id: VAMaxRtg, Offset: 5, Type: typelabel.Uint16, ScaleFactor: "VA_SF", Units: "VA", Label: "Apparent Power Max Rating", Description: "Maximum apparent power rating in voltamperes."},
					{Id: VarMaxInjRtg, Offset: 6, Type: typelabel.Uint16, ScaleFactor: "Var_SF", Units: "Var", Label: "Reactive Power Injected Rating", Description: "Maximum injected reactive power rating in vars."},
					{Id: VarMaxAbsRtg, Offset: 7, Type: typelabel.Uint16, ScaleFactor: "Var_SF", Units: "Var", Label: "Reactive Power Absorbed Rating", Description: "Maximum absorbed reactive power rating in vars."},
					{Id: WChaRteMaxRtg, Offset: 8, Type: typelabel.Uint16, ScaleFactor: "W_SF", Units: "W", Label: "Charge Rate Max Rating", Description: "Maximum active power charge rate in watts."},
					{Id: WDisChaRteMaxRtg, Offset: 9, Type: typelabel.Uint16, ScaleFactor: "W_SF", Units: "W", Label: "Discharge Rate Max Rating", Description: "Maximum active power discharge rate in watts."},
					{Id: VAChaRteMaxRtg, Offset: 10, Type: typelabel.Uint16, ScaleFactor: "VA_SF", Units: "VA", Label: "Charge Rate Max VA Rating", Description: "Maximum apparent power charge rate in voltamperes."},
					{Id: VADisChaRteMaxRtg, Offset: 11, Type: typelabel.Uint16, ScaleFactor: "VA_SF", Units: "VA", Label: "Discharge Rate Max VA Rating", Description: "Maximum apparent power discharge rate in voltamperes."},
					{Id: VNomRtg, Offset: 12, Type: typelabel.Uint16, ScaleFactor: "V_SF", Units: "V", Label: "AC Voltage Nominal Rating", Description: "AC voltage nominal rating."},
					{Id: VMaxRtg, Offset: 13, Type: typelabel.Uint16, ScaleFactor: "V_SF", Units: "V", Label: "AC Voltage Max Rating", Description: "AC voltage maximum rating."},
					{Id: VMinRtg, Offset: 14, Type: typelabel.Uint16, ScaleFactor: "V_SF", Units: "V", Label: "AC Voltage Min Rating", Description: "AC voltage minimum rating."},
					{Id: AMaxRtg, Offset: 15, Type: typelabel.Uint16, ScaleFactor: "A_SF", Units: "A", Label: "AC Current Max Rating", Description: "AC current maximum rating in amps."},
					{Id: PFOvrExtRtg, Offset: 16, Type: typelabel.Uint16, ScaleFactor: "PF_SF", Label: "PF Over-Excited Rating (Unused)", Description: "Unused. Please use WOvrExtRtgPF."},
					{Id: PFUndExtRtg, Offset: 17, Type: typelabel.Uint16, ScaleFactor: "PF_SF", Label: "PF Under-Excited Rating (Unused)", Description: "Unused. Please use WUndExtRtgPF."},
					{Id: ReactSusceptRtg, Offset: 18, Type: typelabel.Uint16, ScaleFactor: "S_SF", Units: "S", Label: "Reactive Susceptance", Description: "Reactive susceptance that remains connected to the Area EPS in the cease to energize and trip state."},
					{Id: NorOpCatRtg, Offset: 19, Type: typelabel.Enum16, Label: "Normal Operating Category", Description: "Normal operating performance category as specified in IEEE 1547-2018."},
					{Id: AbnOpCatRtg, Offset: 20, Type: typelabel.Enum16, Label: "Abnormal Operating Category", Description: "Abnormal operating performance category as specified in IEEE 1547-2018."},
					{Id: CtrlModes, Offset: 21, Type: typelabel.Bitfield32, Label: "Supported Control Modes", Description: "Supported control mode functions."},
					{Id: IntIslandCatRtg, Offset: 23, Type: typelabel.Bitfield16, Label: "Intentional Island Categories", Description: "Intentional island categories."},
					{Id: WMax, Offset: 24, Type: typelabel.Uint16, ScaleFactor: "W_SF", Units: "W", Access: "rw", Label: "Active Power Max Setting", Description: "Maximum active power setting used to adjust maximum active power setting."},
					{Id: WMaxOvrExt, Offset: 25, Type: typelabel.Uint16, ScaleFactor: "W_SF", Units: "W", Access: "rw", Label: "Active Power (Over-Excited) Setting", Description: "Active power setting at specified over-excited power factor in watts."},
					{Id: WOvrExtPF, Offset: 26, Type: typelabel.Uint16, ScaleFactor: "PF_SF", Access: "rw", Label: "Specified Over-Excited PF", Description: "Specified over-excited power factor."},
					{Id: WMaxUndExt, Offset: 27, Type: typelabel.Uint16, ScaleFactor: "W_SF", Units: "W", Access: "rw", Label: "Active Power (Under-Excited) Setting", Description: "Active power setting at specified under-excited power factor in watts."},
					{Id: WUndExtPF, Offset: 28, Type: typelabel.Uint16, ScaleFactor: "PF_SF", Access: "rw", Label: "Specified Under-Excited PF", Description: "Specified under-excited power factor."},
					{Id: VAMax, Offset: 29, Type: typelabel.Uint16, ScaleFactor: "VA_SF", Units: "VA", Access: "rw", Label: "Apparent Power Max Setting", Description: "Maximum apparent power setting used to adjust maximum apparent power rating."},
					{Id: VarMaxInj, Offset: 30, Type: typelabel.Uint16, ScaleFactor: "Var_SF", Units: "Var", Access: "rw", Label: "Reactive Power Injected Setting", Description: "Maximum injected reactive power setting used to adjust maximum injected reactive power rating."},
					{Id: VarMaxAbs, Offset: 31, Type: typelabel.Uint16, ScaleFactor: "Var_SF", Units: "Var", Access: "rw", Label: "Reactive Power Absorbed Setting", Description: "Maximum absorbed reactive power setting used to adjust maximum absorbed reactive power rating."},
					{Id: WChaRteMax, Offset: 32, Type: typelabel.Uint16, ScaleFactor: "W_SF", Units: "W", Access: "rw", Label: "Charge Rate Max Setting", Description: "Maximum active power charge rate setting used to adjust maximum active power charge rate rating."},
					{Id: WDisChaRteMax, Offset: 33, Type: typelabel.Uint16, ScaleFactor: "W_SF", Units: "W", Access: "rw", Label: "Discharge Rate Max Setting", Description: "Maximum active power discharge rate setting used to adjust maximum active power discharge rate rating."},
					{Id: VAChaRteMax, Offset: 34, Type: typelabel.Uint16, ScaleFactor: "VA_SF", Units: "VA", Access: "rw", Label: "Charge Rate Max VA Setting", Description: "Maximum apparent power charge rate setting used to adjust maximum apparent power charge rate rating."},
					{Id: VADisChaRteMax, Offset: 35, Type: typelabel.Uint16, ScaleFactor: "VA_SF", Units: "VA", Access: "rw", Label: "Discharge Rate Max VA Setting", Description: "Maximum apparent power discharge rate setting used to adjust maximum apparent power discharge rate rating."},
					{Id: VNom, Offset: 36, Type: typelabel.Uint16, ScaleFactor: "V_SF", Units: "V", Access: "rw", Label: "Nominal AC Voltage Setting", Description: "Nominal AC voltage setting."},
					{Id: VMax, Offset: 37, Type: typelabel.Uint16, ScaleFactor: "V_SF", Units: "V", Access: "rw", Label: "AC Voltage Max Setting", Description: "AC voltage maximum setting used to adjust AC voltage maximum rating."},
					{Id: VMin, Offset: 38, Type: typelabel.Uint16, ScaleFactor: "V_SF", Units: "V", Access: "rw", Label: "AC Voltage Min Setting", Description: "AC voltage minimum setting used to adjust AC voltage minimum rating."},
					{Id: AMax, Offset: 39, Type: typelabel.Uint16, ScaleFactor: "A_SF", Units: "A", Access: "rw", Label: "AC Current Max Setting", Description: "Maximum AC current setting used to adjust maximum AC current rating."},
					{Id: PFOvrExt, Offset: 40, Type: typelabel.Uint16, ScaleFactor: "PF_SF", Access: "rw", Label: "PF Over-Excited Setting (Unused)", Description: "Unused. Please use WOvrExtPF."},
					{Id: PFUndExt, Offset: 41, Type: typelabel.Uint16, ScaleFactor: "PF_SF", Access: "rw", Label: "PF Under-Excited Setting (Unused)", Description: "Unused. Please use WUndExtPF."},
					{Id: IntIslandCat, Offset: 42, Type: typelabel.Bitfield16, Access: "rw", Label: "Intentional Island Categories", Description: "Intentional island categories."},
					{Id: W_SF, Offset: 43, Type: typelabel.ScaleFactor, Label: "Active Power Scale Factor", Description: "Active power scale factor."},
					{Id: PF_SF, Offset: 44, Type: typelabel.ScaleFactor, Label: "Power Factor Scale Factor", Description: "Power factor scale factor."},
					{Id: VA_SF, Offset: 45, Type: typelabel.ScaleFactor, Label: "Apparent Power Scale Factor", Description: "Apparent power scale factor."},
					{Id: Var_SF, Offset: 46, Type: typelabel.ScaleFactor, Label: "Reactive Power Scale Factor", Description: "Reactive power scale factor."},
					{Id: V_SF, Offset: 47, Type: typelabel.ScaleFactor, Label: "Voltage Scale Factor", Description: "Voltage scale factor."},
					{Id: A_SF, Offset: 48, Type: typelabel.ScaleFactor, Label: "Current Scale Factor", Description: "Current scale factor."},
					{Id: S_SF, Offset: 49, Type: typelabel.ScaleFactor, Label: "Susceptance Scale Factor", Description: "Susceptance scale factor."},
				},
			},
		}})
}
