package model5

// Code generated by ../../generators/models.go. DO NOT EDIT.
// You can regenerate it by running 'go generate ./models' from the directory above.

import (
	"github.com/andig/gosunspec"
	"github.com/andig/gosunspec/smdx"
	"github.com/andig/gosunspec/typelabel"
)

// Block5 - Secure Write Request - Include a digital signature along with the control data

const (
	ModelID          = 5
	ModelLabel       = "Secure Write Request"
	ModelDescription = "Include a digital signature along with the control data"
)

const (
	Alg   = "Alg"
	DS    = "DS"
	Ms    = "Ms"
	N     = "N"
	Off1  = "Off1"
	Off10 = "Off10"
	Off11 = "Off11"
	Off12 = "Off12"
	Off13 = "Off13"
	Off14 = "Off14"
	Off15 = "Off15"
	Off16 = "Off16"
	Off17 = "Off17"
	Off18 = "Off18"
	Off19 = "Off19"
	Off2  = "Off2"
	Off20 = "Off20"
	Off21 = "Off21"
	Off22 = "Off22"
	Off23 = "Off23"
	Off24 = "Off24"
	Off25 = "Off25"
	Off26 = "Off26"
	Off27 = "Off27"
	Off28 = "Off28"
	Off29 = "Off29"
	Off3  = "Off3"
	Off30 = "Off30"
	Off31 = "Off31"
	Off32 = "Off32"
	Off33 = "Off33"
	Off34 = "Off34"
	Off35 = "Off35"
	Off36 = "Off36"
	Off37 = "Off37"
	Off38 = "Off38"
	Off39 = "Off39"
	Off4  = "Off4"
	Off40 = "Off40"
	Off5  = "Off5"
	Off6  = "Off6"
	Off7  = "Off7"
	Off8  = "Off8"
	Off9  = "Off9"
	Role  = "Role"
	Seq   = "Seq"
	Ts    = "Ts"
	Val1  = "Val1"
	Val10 = "Val10"
	Val11 = "Val11"
	Val12 = "Val12"
	Val13 = "Val13"
	Val14 = "Val14"
	Val15 = "Val15"
	Val16 = "Val16"
	Val17 = "Val17"
	Val18 = "Val18"
	Val19 = "Val19"
	Val2  = "Val2"
	Val20 = "Val20"
	Val21 = "Val21"
	Val22 = "Val22"
	Val23 = "Val23"
	Val24 = "Val24"
	Val25 = "Val25"
	Val26 = "Val26"
	Val27 = "Val27"
	Val28 = "Val28"
	Val29 = "Val29"
	Val3  = "Val3"
	Val30 = "Val30"
	Val31 = "Val31"
	Val32 = "Val32"
	Val33 = "Val33"
	Val34 = "Val34"
	Val35 = "Val35"
	Val36 = "Val36"
	Val37 = "Val37"
	Val38 = "Val38"
	Val39 = "Val39"
	Val4  = "Val4"
	Val40 = "Val40"
	Val5  = "Val5"
	Val6  = "Val6"
	Val7  = "Val7"
	Val8  = "Val8"
	Val9  = "Val9"
	X     = "X"
)

type Block5Repeat struct {
	DS uint16 `sunspec:"offset=0,len=1,access=rw"`
}

type Block5 struct {
	X     uint16         `sunspec:"offset=0,len=1,access=rw"`
	Off1  uint16         `sunspec:"offset=1,len=1,access=rw"`
	Val1  uint16         `sunspec:"offset=2,len=1,access=rw"`
	Off2  uint16         `sunspec:"offset=3,len=1,access=rw"`
	Val2  uint16         `sunspec:"offset=4,len=1,access=rw"`
	Off3  uint16         `sunspec:"offset=5,len=1,access=rw"`
	Val3  uint16         `sunspec:"offset=6,len=1,access=rw"`
	Off4  uint16         `sunspec:"offset=7,len=1,access=rw"`
	Val4  uint16         `sunspec:"offset=8,len=1,access=rw"`
	Off5  uint16         `sunspec:"offset=9,len=1,access=rw"`
	Val5  uint16         `sunspec:"offset=10,len=1,access=rw"`
	Off6  uint16         `sunspec:"offset=11,len=1,access=rw"`
	Val6  uint16         `sunspec:"offset=12,len=1,access=rw"`
	Off7  uint16         `sunspec:"offset=13,len=1,access=rw"`
	Val7  uint16         `sunspec:"offset=14,len=1,access=rw"`
	Off8  uint16         `sunspec:"offset=15,len=1,access=rw"`
	Val8  uint16         `sunspec:"offset=16,len=1,access=rw"`
	Off9  uint16         `sunspec:"offset=17,len=1,access=rw"`
	Val9  uint16         `sunspec:"offset=18,len=1,access=rw"`
	Off10 uint16         `sunspec:"offset=19,len=1,access=rw"`
	Val10 uint16         `sunspec:"offset=20,len=1,access=rw"`
	Off11 uint16         `sunspec:"offset=21,len=1,access=rw"`
	Val11 uint16         `sunspec:"offset=22,len=1,access=rw"`
	Off12 uint16         `sunspec:"offset=23,len=1,access=rw"`
	Val12 uint16         `sunspec:"offset=24,len=1,access=rw"`
	Off13 uint16         `sunspec:"offset=25,len=1,access=rw"`
	Val13 uint16         `sunspec:"offset=26,len=1,access=rw"`
	Off14 uint16         `sunspec:"offset=27,len=1,access=rw"`
	Val14 uint16         `sunspec:"offset=28,len=1,access=rw"`
	Off15 uint16         `sunspec:"offset=29,len=1,access=rw"`
	Val15 uint16         `sunspec:"offset=30,len=1,access=rw"`
	Off16 uint16         `sunspec:"offset=31,len=1,access=rw"`
	Val16 uint16         `sunspec:"offset=32,len=1,access=rw"`
	Off17 uint16         `sunspec:"offset=33,len=1,access=rw"`
	Val17 uint16         `sunspec:"offset=34,len=1,access=rw"`
	Off18 uint16         `sunspec:"offset=35,len=1,access=rw"`
	Val18 uint16         `sunspec:"offset=36,len=1,access=rw"`
	Off19 uint16         `sunspec:"offset=37,len=1,access=rw"`
	Val19 uint16         `sunspec:"offset=38,len=1,access=rw"`
	Off20 uint16         `sunspec:"offset=39,len=1,access=rw"`
	Val20 uint16         `sunspec:"offset=40,len=1,access=rw"`
	Off21 uint16         `sunspec:"offset=41,len=1,access=rw"`
	Val21 uint16         `sunspec:"offset=42,len=1,access=rw"`
	Off22 uint16         `sunspec:"offset=43,len=1,access=rw"`
	Val22 uint16         `sunspec:"offset=44,len=1,access=rw"`
	Off23 uint16         `sunspec:"offset=45,len=1,access=rw"`
	Val23 uint16         `sunspec:"offset=46,len=1,access=rw"`
	Off24 uint16         `sunspec:"offset=47,len=1,access=rw"`
	Val24 uint16         `sunspec:"offset=48,len=1,access=rw"`
	Off25 uint16         `sunspec:"offset=49,len=1,access=rw"`
	Val25 uint16         `sunspec:"offset=50,len=1,access=rw"`
	Off26 uint16         `sunspec:"offset=51,len=1,access=rw"`
	Val26 uint16         `sunspec:"offset=52,len=1,access=rw"`
	Off27 uint16         `sunspec:"offset=53,len=1,access=rw"`
	Val27 uint16         `sunspec:"offset=54,len=1,access=rw"`
	Off28 uint16         `sunspec:"offset=55,len=1,access=rw"`
	Val28 uint16         `sunspec:"offset=56,len=1,access=rw"`
	Off29 uint16         `sunspec:"offset=57,len=1,access=rw"`
	Val29 uint16         `sunspec:"offset=58,len=1,access=rw"`
	Off30 uint16         `sunspec:"offset=59,len=1,access=rw"`
	Val30 uint16         `sunspec:"offset=60,len=1,access=rw"`
	Off31 uint16         `sunspec:"offset=61,len=1,access=rw"`
	Val31 uint16         `sunspec:"offset=62,len=1,access=rw"`
	Off32 uint16         `sunspec:"offset=63,len=1,access=rw"`
	Val32 uint16         `sunspec:"offset=64,len=1,access=rw"`
	Off33 uint16         `sunspec:"offset=65,len=1,access=rw"`
	Val33 uint16         `sunspec:"offset=66,len=1,access=rw"`
	Off34 uint16         `sunspec:"offset=67,len=1,access=rw"`
	Val34 uint16         `sunspec:"offset=68,len=1,access=rw"`
	Off35 uint16         `sunspec:"offset=69,len=1,access=rw"`
	Val35 uint16         `sunspec:"offset=70,len=1,access=rw"`
	Off36 uint16         `sunspec:"offset=71,len=1,access=rw"`
	Val36 uint16         `sunspec:"offset=72,len=1,access=rw"`
	Off37 uint16         `sunspec:"offset=73,len=1,access=rw"`
	Val37 uint16         `sunspec:"offset=74,len=1,access=rw"`
	Off38 uint16         `sunspec:"offset=75,len=1,access=rw"`
	Val38 uint16         `sunspec:"offset=76,len=1,access=rw"`
	Off39 uint16         `sunspec:"offset=77,len=1,access=rw"`
	Val39 uint16         `sunspec:"offset=78,len=1,access=rw"`
	Off40 uint16         `sunspec:"offset=79,len=1,access=rw"`
	Val40 uint16         `sunspec:"offset=80,len=1,access=rw"`
	Ts    uint32         `sunspec:"offset=81,len=2,access=rw"`
	Ms    uint16         `sunspec:"offset=83,len=1,access=rw"`
	Seq   uint16         `sunspec:"offset=84,len=1,access=rw"`
	Role  uint16         `sunspec:"offset=85,len=1,access=rw"`
	Alg   sunspec.Enum16 `sunspec:"offset=86,len=1,access=rw"`
	N     uint16         `sunspec:"offset=87,len=1,access=rw"`

	Repeats []Block5Repeat
}

func (block *Block5) GetId() sunspec.ModelId {
	return ModelID
}

func init() {
	smdx.RegisterModel(&smdx.ModelElement{
		Id:     ModelID,
		Name:   "model_5",
		Length: 89,
		Blocks: []smdx.BlockElement{
			{
				Length: 88,
				Points: []smdx.PointElement{
					{Id: X, Offset: 0, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true, Label: "X", Description: "Number of (offset, value) pairs being written"},
					{Id: Off1, Offset: 1, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true, Label: "Offset1", Description: "Offset of control register to write value to"},
					{Id: Val1, Offset: 2, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true, Label: "Value1", Description: "Value to write to control register at offset"},
					{Id: Off2, Offset: 3, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true},
					{Id: Val2, Offset: 4, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true},
					{Id: Off3, Offset: 5, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true},
					{Id: Val3, Offset: 6, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true},
					{Id: Off4, Offset: 7, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true},
					{Id: Val4, Offset: 8, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true},
					{Id: Off5, Offset: 9, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true},
					{Id: Val5, Offset: 10, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true},
					{Id: Off6, Offset: 11, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true},
					{Id: Val6, Offset: 12, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true},
					{Id: Off7, Offset: 13, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true},
					{Id: Val7, Offset: 14, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true},
					{Id: Off8, Offset: 15, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true},
					{Id: Val8, Offset: 16, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true},
					{Id: Off9, Offset: 17, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true},
					{Id: Val9, Offset: 18, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true},
					{Id: Off10, Offset: 19, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true},
					{Id: Val10, Offset: 20, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true},
					{Id: Off11, Offset: 21, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true},
					{Id: Val11, Offset: 22, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true},
					{Id: Off12, Offset: 23, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true},
					{Id: Val12, Offset: 24, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true},
					{Id: Off13, Offset: 25, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true},
					{Id: Val13, Offset: 26, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true},
					{Id: Off14, Offset: 27, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true},
					{Id: Val14, Offset: 28, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true},
					{Id: Off15, Offset: 29, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true},
					{Id: Val15, Offset: 30, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true},
					{Id: Off16, Offset: 31, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true},
					{Id: Val16, Offset: 32, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true},
					{Id: Off17, Offset: 33, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true},
					{Id: Val17, Offset: 34, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true},
					{Id: Off18, Offset: 35, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true},
					{Id: Val18, Offset: 36, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true},
					{Id: Off19, Offset: 37, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true},
					{Id: Val19, Offset: 38, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true},
					{Id: Off20, Offset: 39, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true},
					{Id: Val20, Offset: 40, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true},
					{Id: Off21, Offset: 41, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true},
					{Id: Val21, Offset: 42, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true},
					{Id: Off22, Offset: 43, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true},
					{Id: Val22, Offset: 44, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true},
					{Id: Off23, Offset: 45, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true},
					{Id: Val23, Offset: 46, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true},
					{Id: Off24, Offset: 47, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true},
					{Id: Val24, Offset: 48, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true},
					{Id: Off25, Offset: 49, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true},
					{Id: Val25, Offset: 50, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true},
					{Id: Off26, Offset: 51, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true},
					{Id: Val26, Offset: 52, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true},
					{Id: Off27, Offset: 53, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true},
					{Id: Val27, Offset: 54, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true},
					{Id: Off28, Offset: 55, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true},
					{Id: Val28, Offset: 56, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true},
					{Id: Off29, Offset: 57, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true},
					{Id: Val29, Offset: 58, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true},
					{Id: Off30, Offset: 59, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true},
					{Id: Val30, Offset: 60, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true},
					{Id: Off31, Offset: 61, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true},
					{Id: Val31, Offset: 62, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true},
					{Id: Off32, Offset: 63, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true},
					{Id: Val32, Offset: 64, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true},
					{Id: Off33, Offset: 65, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true},
					{Id: Val33, Offset: 66, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true},
					{Id: Off34, Offset: 67, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true},
					{Id: Val34, Offset: 68, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true},
					{Id: Off35, Offset: 69, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true},
					{Id: Val35, Offset: 70, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true},
					{Id: Off36, Offset: 71, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true},
					{Id: Val36, Offset: 72, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true},
					{Id: Off37, Offset: 73, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true},
					{Id: Val37, Offset: 74, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true},
					{Id: Off38, Offset: 75, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true},
					{Id: Val38, Offset: 76, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true},
					{Id: Off39, Offset: 77, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true},
					{Id: Val39, Offset: 78, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true},
					{Id: Off40, Offset: 79, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true},
					{Id: Val40, Offset: 80, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true},
					{Id: Ts, Offset: 81, Type: typelabel.Uint32, Access: "rw", Length: 2, Mandatory: true, Label: "Timestamp", Description: "Timestamp value is the number of seconds since January 1, 2000"},
					{Id: Ms, Offset: 83, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true, Label: "Milliseconds", Description: "Millisecond counter 0-999"},
					{Id: Seq, Offset: 84, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true, Label: "Sequence", Description: "Sequence number of request"},
					{Id: Role, Offset: 85, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true, Label: "Role", Description: "Signing key used 0-5"},
					{Id: Alg, Offset: 86, Type: typelabel.Enum16, Access: "rw", Length: 1, Mandatory: true, Label: "Algorithm", Description: "Algorithm used to compute the digital signature"},
					{Id: N, Offset: 87, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true, Label: "N", Description: "Number of registers comprising the digital signature."},
				},
			},
			{Name: "repeating",
				Length: 1,
				Type:   "repeating",
				Points: []smdx.PointElement{
					{Id: DS, Offset: 0, Type: typelabel.Uint16, Access: "rw", Length: 1, Mandatory: true, Label: "DS", Description: "Digital Signature"},
				},
			},
		}})
}
