package model401

// Code generated by ../../generators/models.go. DO NOT EDIT.
// You can regenerate it by running 'go generate ./models' from the directory above.

import (
	"github.com/andig/gosunspec"
	"github.com/andig/gosunspec/smdx"
	"github.com/andig/gosunspec/typelabel"
)

// Block401 - String Combiner (Current) - A basic string combiner

const (
	ModelID          = 401
	ModelLabel       = "String Combiner (Current)"
	ModelDescription = "A basic string combiner"
)

const (
	DCA      = "DCA"
	DCAMax   = "DCAMax"
	DCA_SF   = "DCA_SF"
	DCAhr    = "DCAhr"
	DCAhr_SF = "DCAhr_SF"
	DCV      = "DCV"
	DCV_SF   = "DCV_SF"
	Evt      = "Evt"
	EvtVnd   = "EvtVnd"
	InDCA    = "InDCA"
	InDCAhr  = "InDCAhr"
	InEvt    = "InEvt"
	InEvtVnd = "InEvtVnd"
	InID     = "InID"
	N        = "N"
	Tmp      = "Tmp"
)

type Block401Repeat struct {
	InID     uint16             `sunspec:"offset=0,len=1,access=r"`
	InEvt    sunspec.Bitfield32 `sunspec:"offset=1,len=2,access=r"`
	InEvtVnd sunspec.Bitfield32 `sunspec:"offset=3,len=2,access=r"`
	InDCA    int16              `sunspec:"offset=5,len=1,sf=DCA_SF,access=r"`
	InDCAhr  uint32             `sunspec:"offset=6,len=2,sf=DCAhr_SF,access=r"`
}

type Block401 struct {
	DCA_SF   sunspec.ScaleFactor `sunspec:"offset=0,len=1,access=r"`
	DCAhr_SF sunspec.ScaleFactor `sunspec:"offset=1,len=1,access=r"`
	DCV_SF   sunspec.ScaleFactor `sunspec:"offset=2,len=1,access=r"`
	DCAMax   uint16              `sunspec:"offset=3,len=1,sf=DCA_SF,access=r"`
	N        sunspec.Count       `sunspec:"offset=4,len=1,access=r"`
	Evt      sunspec.Bitfield32  `sunspec:"offset=5,len=2,access=r"`
	EvtVnd   sunspec.Bitfield32  `sunspec:"offset=7,len=2,access=r"`
	DCA      int16               `sunspec:"offset=9,len=1,sf=DCA_SF,access=r"`
	DCAhr    uint32              `sunspec:"offset=10,len=2,sf=DCAhr_SF,access=r"`
	DCV      uint16              `sunspec:"offset=12,len=1,sf=DCV_SF,access=r"`
	Tmp      int16               `sunspec:"offset=13,len=1,access=r"`

	Repeats []Block401Repeat
}

func (block *Block401) GetId() sunspec.ModelId {
	return ModelID
}

func init() {
	smdx.RegisterModel(&smdx.ModelElement{
		Id:     ModelID,
		Name:   "string_combiner",
		Length: 22,
		Blocks: []smdx.BlockElement{
			{
				Length: 14,
				Points: []smdx.PointElement{
					{Id: DCA_SF, Offset: 0, Type: typelabel.ScaleFactor, Access: "r", Length: 1, Mandatory: true},
					{Id: DCAhr_SF, Offset: 1, Type: typelabel.ScaleFactor, Access: "r", Length: 1},
					{Id: DCV_SF, Offset: 2, Type: typelabel.ScaleFactor, Access: "r", Length: 1},
					{Id: DCAMax, Offset: 3, Type: typelabel.Uint16, ScaleFactor: "DCA_SF", Units: "A", Access: "r", Length: 1, Mandatory: true, Label: "Rating", Description: "Maximum DC Current Rating"},
					{Id: N, Offset: 4, Type: typelabel.Count, Access: "r", Length: 1, Mandatory: true, Label: "N", Description: "Number of Inputs"},
					{Id: Evt, Offset: 5, Type: typelabel.Bitfield32, Access: "r", Length: 2, Mandatory: true, Label: "Event", Description: "Bitmask value.  Events"},
					{Id: EvtVnd, Offset: 7, Type: typelabel.Bitfield32, Access: "r", Length: 2, Label: "Vendor Event", Description: "Bitmask value.  Vendor defined events"},
					{Id: DCA, Offset: 9, Type: typelabel.Int16, ScaleFactor: "DCA_SF", Units: "A", Access: "r", Length: 1, Mandatory: true, Label: "Amps", Description: "Total measured current"},
					{Id: DCAhr, Offset: 10, Type: typelabel.Uint32, ScaleFactor: "DCAhr_SF", Units: "Ah", Access: "r", Length: 2, Label: "Amp-hours", Description: "Total metered Amp-hours"},
					{Id: DCV, Offset: 12, Type: typelabel.Uint16, ScaleFactor: "DCV_SF", Units: "V", Access: "r", Length: 1, Label: "Voltage", Description: "Output Voltage"},
					{Id: Tmp, Offset: 13, Type: typelabel.Int16, Units: "C", Access: "r", Length: 1, Label: "Temp", Description: "Internal operating temperature"},
				},
			},
			{Name: "string",
				Length: 8,
				Type:   "repeating",
				Points: []smdx.PointElement{
					{Id: InID, Offset: 0, Type: typelabel.Uint16, Access: "r", Length: 1, Mandatory: true, Label: "ID", Description: "Uniquely identifies this input set"},
					{Id: InEvt, Offset: 1, Type: typelabel.Bitfield32, Access: "r", Length: 2, Mandatory: true, Label: "Input Event", Description: "String Input Event Flags"},
					{Id: InEvtVnd, Offset: 3, Type: typelabel.Bitfield32, Access: "r", Length: 2, Label: "Input Event Vendor", Description: "String Input Vendor Event Flags"},
					{Id: InDCA, Offset: 5, Type: typelabel.Int16, ScaleFactor: "DCA_SF", Units: "A", Access: "r", Length: 1, Mandatory: true, Label: "Amps", Description: "String Input Current"},
					{Id: InDCAhr, Offset: 6, Type: typelabel.Uint32, ScaleFactor: "DCAhr_SF", Units: "Ah", Access: "r", Length: 2, Label: "Amp-hours", Description: "String Input Amp-Hours"},
				},
			},
		}})
}
