package model801

// Code generated by ../../generators/json/models.go. DO NOT EDIT.
// You can regenerate it by running 'make spec' from the project root.

import (
	"github.com/andig/gosunspec"
	"github.com/andig/gosunspec/typelabel"
	"github.com/andig/gosunspec/types"
)

// Block801 - Energy Storage Base Model (DEPRECATED) - This model has been deprecated.

const (
	ModelID          = 801
	ModelLabel       = "Energy Storage Base Model (DEPRECATED)"
	ModelDescription = "This model has been deprecated."
)

const (
	DEPRECATED = "DEPRECATED"
)

type Block801 struct {
	DEPRECATED sunspec.Enum16 `sunspec:"offset=0"`
}

func (block *Block801) GetId() sunspec.ModelId {
	return ModelID
}

func init() {
	types.RegisterModel(&types.Model{
		Id:          ModelID,
		Name:        "storage",
		Label:       "Energy Storage Base Model (DEPRECATED)",
		Description: "This model has been deprecated.",
		Length:      1,
		Blocks: []types.Block{
			{
				Length: 1,
				Type:   types.BlockFixed,
				Points: []types.Point{
					{Id: DEPRECATED, Offset: 0, Type: typelabel.Enum16, Mandatory: true, Label: "Deprecated Model", Description: "This model has been deprecated."},
				},
			},
		}})
}
