package model64414

// Code generated by ../../generators/json/models.go. DO NOT EDIT.
// You can regenerate it by running 'make spec' from the project root.

import (
	"github.com/andig/gosunspec"
	"github.com/andig/gosunspec/typelabel"
	"github.com/andig/gosunspec/types"
)

// Block64414 - DER Simulation Controls - Configuration parameters for the DER device simulator.

const (
	ModelID          = 64414
	ModelLabel       = "DER Simulation Controls"
	ModelDescription = "Configuration parameters for the DER device simulator."
)

const (
	GridFrequency         = "GridFrequency"
	GridModelSource       = "GridModelSource"
	GridVoltageA          = "GridVoltageA"
	GridVoltageB          = "GridVoltageB"
	GridVoltageC          = "GridVoltageC"
	Irradiance            = "Irradiance"
	IrradianceModelSource = "IrradianceModelSource"
	Temperature           = "Temperature"
	Time                  = "Time"
)

type Block64414 struct {
	Time                  string  `sunspec:"offset=0,len=10"`
	Temperature           float32 `sunspec:"offset=10,access=rw"`
	GridModelSource       string  `sunspec:"offset=12,len=32,access=rw"`
	IrradianceModelSource string  `sunspec:"offset=44,len=32,access=rw"`
	Irradiance            float32 `sunspec:"offset=76,access=rw"`
	GridVoltageA          float32 `sunspec:"offset=78,access=rw"`
	GridVoltageB          float32 `sunspec:"offset=80,access=rw"`
	GridVoltageC          float32 `sunspec:"offset=82,access=rw"`
	GridFrequency         float32 `sunspec:"offset=84,access=rw"`
}

func (block *Block64414) GetId() sunspec.ModelId {
	return ModelID
}

func init() {
	types.RegisterModel(&types.Model{
		Id:          ModelID,
		Name:        "DERSimControls",
		Label:       "DER Simulation Controls",
		Description: "Configuration parameters for the DER device simulator.",
		Length:      86,
		Blocks: []types.Block{
			{
				Length: 86,
				Type:   types.BlockFixed,
				Points: []types.Point{
					{Id: Time, Offset: 0, Type: typelabel.String, Length: 10, Label: "Time offset", Description: "Time offset for simulation formatted 'HH:MM:SS'"},
					{Id: Temperature, Offset: 10, Type: typelabel.Float32, Access: "rw"},
					{Id: GridModelSource, Offset: 12, Type: typelabel.String, Access: "rw", Length: 32},
					{Id: IrradianceModelSource, Offset: 44, Type: typelabel.String, Access: "rw", Length: 32},
					{Id: Irradiance, Offset: 76, Type: typelabel.Float32, Access: "rw"},
					{Id: GridVoltageA, Offset: 78, Type: typelabel.Float32, Access: "rw"},
					{Id: GridVoltageB, Offset: 80, Type: typelabel.Float32, Access: "rw"},
					{Id: GridVoltageC, Offset: 82, Type: typelabel.Float32, Access: "rw"},
					{Id: GridFrequency, Offset: 84, Type: typelabel.Float32, Access: "rw"},
				},
			},
		}})
}
