package model713

// Code generated by ../../generators/json/models.go. DO NOT EDIT.
// You can regenerate it by running 'make spec' from the project root.

import (
	"github.com/andig/gosunspec"
	"github.com/andig/gosunspec/typelabel"
	"github.com/andig/gosunspec/types"
)

// Block713 - DER Storage Capacity - DER storage capacity.

const (
	ModelID          = 713
	ModelLabel       = "DER Storage Capacity"
	ModelDescription = "DER storage capacity."
)

const (
	Pct_SF  = "Pct_SF"
	SoC     = "SoC"
	SoH     = "SoH"
	Sta     = "Sta"
	WHAvail = "WHAvail"
	WHRtg   = "WHRtg"
	WH_SF   = "WH_SF"
)

type Block713 struct {
	WHRtg   uint16              `sunspec:"offset=0,sf=WH_SF"`
	WHAvail uint16              `sunspec:"offset=1,sf=WH_SF"`
	SoC     uint16              `sunspec:"offset=2,sf=Pct_SF"`
	SoH     uint16              `sunspec:"offset=3,sf=Pct_SF"`
	Sta     sunspec.Enum16      `sunspec:"offset=4"`
	WH_SF   sunspec.ScaleFactor `sunspec:"offset=5"`
	Pct_SF  sunspec.ScaleFactor `sunspec:"offset=6"`
}

func (block *Block713) GetId() sunspec.ModelId {
	return ModelID
}

func init() {
	types.RegisterModel(&types.Model{
		Id:          ModelID,
		Name:        "DERStorageCapacity",
		Label:       "DER Storage Capacity",
		Description: "DER storage capacity.",
		Length:      7,
		Blocks: []types.Block{
			{
				Length: 7,
				Type:   types.BlockFixed,
				Points: []types.Point{
					{Id: WHRtg, Offset: 0, Type: typelabel.Uint16, ScaleFactor: "WH_SF", Units: "WH", Label: "Energy Rating", Description: "Energy rating of the DER storage."},
					{Id: WHAvail, Offset: 1, Type: typelabel.Uint16, ScaleFactor: "WH_SF", Units: "WH", Label: "Energy Available", Description: "Energy available of the DER storage (WHAvail = WHRtg * SoC * SoH)"},
					{Id: SoC, Offset: 2, Type: typelabel.Uint16, ScaleFactor: "Pct_SF", Units: "Pct", Label: "State of Charge", Description: "State of charge of the DER storage."},
					{Id: SoH, Offset: 3, Type: typelabel.Uint16, ScaleFactor: "Pct_SF", Units: "Pct", Label: "State of Health", Description: "State of health of the DER storage."},
					{Id: Sta, Offset: 4, Type: typelabel.Enum16, Label: "Status", Description: "Storage status."},
					{Id: WH_SF, Offset: 5, Type: typelabel.ScaleFactor, Label: "Energy Scale Factor", Description: "Scale factor for energy capacity."},
					{Id: Pct_SF, Offset: 6, Type: typelabel.ScaleFactor, Label: "Percent Scale Factor", Description: "Scale factor for percentage."},
				},
			},
		}})
}
