package model64111

// Code generated by ../../generators/models/models.go. DO NOT EDIT.
// You can regenerate it by running 'go generate ./models' from the directory above.

import (
	"github.com/andig/gosunspec"
	"github.com/andig/gosunspec/typelabel"
	"github.com/andig/gosunspec/types"
)

// Block64111 - Basic Charge Controller -

const (
	ModelID          = 64111
	ModelLabel       = "Basic Charge Controller"
	ModelDescription = ""
)

const (
	AH_SF           = "AH_SF"
	A_SF            = "A_SF"
	ArrayV          = "ArrayV"
	BattV           = "BattV"
	ChargerSt       = "ChargerSt"
	InputA          = "InputA"
	KWH_SF          = "KWH_SF"
	LifeTimeAHOut   = "LifeTimeAHOut"
	LifeTimeKWHOut  = "LifeTimeKWHOut"
	LifeTimeMaxBatt = "LifeTimeMaxBatt"
	LifeTimeMaxOut  = "LifeTimeMaxOut"
	LifeTimeMaxVOC  = "LifeTimeMaxVOC"
	OutputA         = "OutputA"
	OutputW         = "OutputW"
	P_SF            = "P_SF"
	Port            = "Port"
	TodayAHOutput   = "TodayAHOutput"
	TodayMaxBatV    = "TodayMaxBatV"
	TodayMaxVOC     = "TodayMaxVOC"
	TodayMinBatV    = "TodayMinBatV"
	TodaykWhOutput  = "TodaykWhOutput"
	VOCV            = "VOCV"
	V_SF            = "V_SF"
)

type Block64111 struct {
	Port            uint16              `sunspec:"offset=0,len=1"`
	V_SF            sunspec.ScaleFactor `sunspec:"offset=1,len=1"`
	A_SF            sunspec.ScaleFactor `sunspec:"offset=2,len=1"`
	P_SF            sunspec.ScaleFactor `sunspec:"offset=3,len=1"`
	AH_SF           sunspec.ScaleFactor `sunspec:"offset=4,len=1"`
	KWH_SF          sunspec.ScaleFactor `sunspec:"offset=5,len=1"`
	BattV           uint16              `sunspec:"offset=6,len=1,sf=V_SF"`
	ArrayV          uint16              `sunspec:"offset=7,len=1,sf=V_SF"`
	OutputA         uint16              `sunspec:"offset=8,len=1,sf=A_SF"`
	InputA          uint16              `sunspec:"offset=9,len=1,sf=P_SF"`
	ChargerSt       sunspec.Enum16      `sunspec:"offset=10,len=1"`
	OutputW         uint16              `sunspec:"offset=11,len=1,sf=P_SF"`
	TodayMinBatV    uint16              `sunspec:"offset=12,len=1,sf=V_SF"`
	TodayMaxBatV    uint16              `sunspec:"offset=13,len=1,sf=V_SF"`
	VOCV            uint16              `sunspec:"offset=14,len=1,sf=V_SF"`
	TodayMaxVOC     uint16              `sunspec:"offset=15,len=1,sf=V_SF"`
	TodaykWhOutput  uint16              `sunspec:"offset=16,len=1,sf=KWH_SF"`
	TodayAHOutput   uint16              `sunspec:"offset=17,len=1,sf=AH_SF"`
	LifeTimeKWHOut  uint16              `sunspec:"offset=18,len=1,sf=P_SF"`
	LifeTimeAHOut   uint16              `sunspec:"offset=19,len=1,sf=KWH_SF"`
	LifeTimeMaxOut  uint16              `sunspec:"offset=20,len=1,sf=P_SF"`
	LifeTimeMaxBatt uint16              `sunspec:"offset=21,len=1,sf=V_SF"`
	LifeTimeMaxVOC  uint16              `sunspec:"offset=22,len=1,sf=V_SF"`
}

func (block *Block64111) GetId() sunspec.ModelId {
	return ModelID
}

func init() {
	types.RegisterModel(&types.Model{
		Id:          ModelID,
		Name:        "",
		Label:       "Basic Charge Controller",
		Description: "",
		Length:      23,
		Blocks: []types.Block{
			{
				Length: 23,
				Type:   types.BlockFixed,
				Points: []types.Point{
					{Id: Port, Offset: 0, Type: typelabel.Uint16, Length: 1, Mandatory: true, Label: "Port Number", Description: ""},
					{Id: V_SF, Offset: 1, Type: typelabel.ScaleFactor, Length: 1, Mandatory: true},
					{Id: A_SF, Offset: 2, Type: typelabel.ScaleFactor, Length: 1, Mandatory: true},
					{Id: P_SF, Offset: 3, Type: typelabel.ScaleFactor, Length: 1, Mandatory: true},
					{Id: AH_SF, Offset: 4, Type: typelabel.ScaleFactor, Length: 1, Mandatory: true},
					{Id: KWH_SF, Offset: 5, Type: typelabel.ScaleFactor, Length: 1, Mandatory: true},
					{Id: BattV, Offset: 6, Type: typelabel.Uint16, ScaleFactor: "V_SF", Units: "V", Length: 1, Mandatory: true, Label: "Battery Voltage", Description: ""},
					{Id: ArrayV, Offset: 7, Type: typelabel.Uint16, ScaleFactor: "V_SF", Units: "V", Length: 1, Mandatory: true, Label: "Array Voltage", Description: ""},
					{Id: OutputA, Offset: 8, Type: typelabel.Uint16, ScaleFactor: "A_SF", Units: "A", Length: 1, Mandatory: true, Label: "Output Current", Description: ""},
					{Id: InputA, Offset: 9, Type: typelabel.Uint16, ScaleFactor: "P_SF", Units: "A", Length: 1, Mandatory: true, Label: "Array Current", Description: ""},
					{Id: ChargerSt, Offset: 10, Type: typelabel.Enum16, Length: 1, Mandatory: true, Label: "Operating State", Description: ""},
					{Id: OutputW, Offset: 11, Type: typelabel.Uint16, ScaleFactor: "P_SF", Units: "W", Length: 1, Mandatory: true, Label: "Output Wattage", Description: ""},
					{Id: TodayMinBatV, Offset: 12, Type: typelabel.Uint16, ScaleFactor: "V_SF", Units: "V", Length: 1, Mandatory: true, Label: "Today's Minimum Battery Voltage", Description: ""},
					{Id: TodayMaxBatV, Offset: 13, Type: typelabel.Uint16, ScaleFactor: "V_SF", Units: "V", Length: 1, Mandatory: true, Label: "Today's Maximum Battery Voltage", Description: ""},
					{Id: VOCV, Offset: 14, Type: typelabel.Uint16, ScaleFactor: "V_SF", Units: "V", Length: 1, Mandatory: true, Label: "VOC", Description: ""},
					{Id: TodayMaxVOC, Offset: 15, Type: typelabel.Uint16, ScaleFactor: "V_SF", Units: "V", Length: 1, Mandatory: true, Label: "Today's Maximum VOC", Description: ""},
					{Id: TodaykWhOutput, Offset: 16, Type: typelabel.Uint16, ScaleFactor: "KWH_SF", Units: "kWh", Length: 1, Mandatory: true, Label: "Today's kWh", Description: ""},
					{Id: TodayAHOutput, Offset: 17, Type: typelabel.Uint16, ScaleFactor: "AH_SF", Units: "AH", Length: 1, Mandatory: true, Label: "Today's AH", Description: ""},
					{Id: LifeTimeKWHOut, Offset: 18, Type: typelabel.Uint16, ScaleFactor: "P_SF", Units: "kWh", Length: 1, Mandatory: true, Label: "Lifetime kWh", Description: ""},
					{Id: LifeTimeAHOut, Offset: 19, Type: typelabel.Uint16, ScaleFactor: "KWH_SF", Units: "kAH", Length: 1, Mandatory: true, Label: "Lifetime kAH", Description: ""},
					{Id: LifeTimeMaxOut, Offset: 20, Type: typelabel.Uint16, ScaleFactor: "P_SF", Units: "W", Length: 1, Mandatory: true, Label: "Lifetime Maximum Output Wattage", Description: ""},
					{Id: LifeTimeMaxBatt, Offset: 21, Type: typelabel.Uint16, ScaleFactor: "V_SF", Units: "V", Length: 1, Mandatory: true, Label: "Lifetime Maximum Battery Voltage", Description: ""},
					{Id: LifeTimeMaxVOC, Offset: 22, Type: typelabel.Uint16, ScaleFactor: "V_SF", Units: "V", Length: 1, Mandatory: true, Label: "Lifetime Maximum VOC Voltage", Description: ""},
				},
			},
		}})
}
