package model64415

// Code generated by ../../generators/json/models.go. DO NOT EDIT.
// You can regenerate it by running 'make spec' from the project root.

import (
	"github.com/andig/gosunspec"
	"github.com/andig/gosunspec/typelabel"
	"github.com/andig/gosunspec/types"
)

// Block64415 - CSIP Client Control - CSIP Client Control for Alarms and Error tests

const (
	ModelID          = 64415
	ModelLabel       = "CSIP Client Control"
	ModelDescription = "CSIP Client Control for Alarms and Error tests"
)

const (
	COMM004Cert        = "COMM004Cert"
	HTTPMsg            = "HTTPMsg"
	LogEventEna        = "LogEventEna"
	SubscribedResource = "SubscribedResource"
	SubscriptionEna    = "SubscriptionEna"
)

type Block64415 struct {
	LogEventEna        sunspec.Enum16 `sunspec:"offset=0,access=rw"`
	HTTPMsg            sunspec.Enum16 `sunspec:"offset=1,access=rw"`
	COMM004Cert        sunspec.Enum16 `sunspec:"offset=2,access=rw"`
	SubscribedResource string         `sunspec:"offset=3,len=64,access=rw"`
	SubscriptionEna    sunspec.Enum16 `sunspec:"offset=67,access=rw"`
}

func (block *Block64415) GetId() sunspec.ModelId {
	return ModelID
}

func init() {
	types.RegisterModel(&types.Model{
		Id:          ModelID,
		Name:        "CSIPControl",
		Label:       "CSIP Client Control",
		Description: "CSIP Client Control for Alarms and Error tests",
		Length:      68,
		Blocks: []types.Block{
			{
				Length: 68,
				Type:   types.BlockFixed,
				Points: []types.Point{
					{Id: LogEventEna, Offset: 0, Type: typelabel.Enum16, Access: "rw", Label: "LogEvent Mode Enable", Description: "Enable or disable the LogEvent mode"},
					{Id: HTTPMsg, Offset: 1, Type: typelabel.Enum16, Access: "rw", Label: "HTTP Message Mode Enable", Description: "Enable or disable the HTTP Message mode"},
					{Id: COMM004Cert, Offset: 2, Type: typelabel.Enum16, Access: "rw", Label: "COMM-004 Certificate", Description: "Select COMM-004 certificate type"},
					{Id: SubscribedResource, Offset: 3, Type: typelabel.String, Access: "rw", Length: 64, Label: "Subscribed Resource URL", Description: "The URL of the resource to subscribe to"},
					{Id: SubscriptionEna, Offset: 67, Type: typelabel.Enum16, Access: "rw", Label: "Subscribtion Enable", Description: "Enable or disable the Subscription mode"},
				},
			},
		}})
}
