package model145

// Code generated by ../../generators/json/models.go. DO NOT EDIT.
// You can regenerate it by running 'make spec' from the project root.

import (
	"github.com/andig/gosunspec"
	"github.com/andig/gosunspec/typelabel"
	"github.com/andig/gosunspec/types"
)

// Block145 - Extended Settings - Inverter controls extended settings

const (
	ModelID          = 145
	ModelLabel       = "Extended Settings"
	ModelDescription = "Inverter controls extended settings "
)

const (
	AGra         = "AGra"
	ConnRmpDnRte = "ConnRmpDnRte"
	ConnRmpUpRte = "ConnRmpUpRte"
	EmgRmpDnRte  = "EmgRmpDnRte"
	EmgRmpUpRte  = "EmgRmpUpRte"
	NomRmpDnRte  = "NomRmpDnRte"
	NomRmpUpRte  = "NomRmpUpRte"
	Rmp_SF       = "Rmp_SF"
)

type Block145 struct {
	NomRmpUpRte  uint16              `sunspec:"offset=0,sf=Rmp_SF,access=rw"`
	NomRmpDnRte  uint16              `sunspec:"offset=1,sf=Rmp_SF,access=rw"`
	EmgRmpUpRte  uint16              `sunspec:"offset=2,sf=Rmp_SF,access=rw"`
	EmgRmpDnRte  uint16              `sunspec:"offset=3,sf=Rmp_SF,access=rw"`
	ConnRmpUpRte uint16              `sunspec:"offset=4,sf=Rmp_SF,access=rw"`
	ConnRmpDnRte uint16              `sunspec:"offset=5,sf=Rmp_SF,access=rw"`
	AGra         uint16              `sunspec:"offset=6,sf=Rmp_SF,access=rw"`
	Rmp_SF       sunspec.ScaleFactor `sunspec:"offset=7"`
}

func (block *Block145) GetId() sunspec.ModelId {
	return ModelID
}

func init() {
	types.RegisterModel(&types.Model{
		Id:          ModelID,
		Name:        "ext_settings",
		Label:       "Extended Settings",
		Description: "Inverter controls extended settings ",
		Length:      8,
		Blocks: []types.Block{
			{
				Length: 8,
				Type:   types.BlockFixed,
				Points: []types.Point{
					{Id: NomRmpUpRte, Offset: 0, Type: typelabel.Uint16, ScaleFactor: "Rmp_SF", Units: "Pct", Access: "rw", Label: "Ramp Up Rate", Description: "Ramp up rate as a percentage of max current."},
					{Id: NomRmpDnRte, Offset: 1, Type: typelabel.Uint16, ScaleFactor: "Rmp_SF", Units: "Pct", Access: "rw", Label: "NomRmpDnRte", Description: "Ramp down rate as a percentage of max current."},
					{Id: EmgRmpUpRte, Offset: 2, Type: typelabel.Uint16, ScaleFactor: "Rmp_SF", Units: "Pct", Access: "rw", Label: "Emergency Ramp Up Rate", Description: "Emergency ramp up rate as a percentage of max current."},
					{Id: EmgRmpDnRte, Offset: 3, Type: typelabel.Uint16, ScaleFactor: "Rmp_SF", Units: "Pct", Access: "rw", Label: "Emergency Ramp Down Rate", Description: "Emergency ramp down rate as a percentage of max current."},
					{Id: ConnRmpUpRte, Offset: 4, Type: typelabel.Uint16, ScaleFactor: "Rmp_SF", Units: "Pct", Access: "rw", Label: "Connect Ramp Up Rate", Description: "Connect ramp up rate as a percentage of max current."},
					{Id: ConnRmpDnRte, Offset: 5, Type: typelabel.Uint16, ScaleFactor: "Rmp_SF", Units: "Pct", Access: "rw", Label: "Connect Ramp Down Rate", Description: "Connect ramp down rate as a percentage of max current."},
					{Id: AGra, Offset: 6, Type: typelabel.Uint16, ScaleFactor: "Rmp_SF", Units: "Pct", Access: "rw", Label: "Default Ramp Rate", Description: "Ramp rate specified in percent of max current."},
					{Id: Rmp_SF, Offset: 7, Type: typelabel.ScaleFactor, Label: "Ramp Rate Scale Factor", Description: "Ramp Rate Scale Factor"},
				},
			},
		}})
}
