package model711

// Code generated by ../../generators/json/models.go. DO NOT EDIT.
// You can regenerate it by running 'make spec' from the project root.

import (
	"github.com/andig/gosunspec"
	"github.com/andig/gosunspec/typelabel"
	"github.com/andig/gosunspec/types"
)

// Block711 - DER Frequency Droop - DER Frequency Droop model.

const (
	ModelID          = 711
	ModelLabel       = "DER Frequency Droop"
	ModelDescription = "DER Frequency Droop model."
)

const (
	AdptCtlReq  = "AdptCtlReq"
	AdptCtlRslt = "AdptCtlRslt"
	DbOf        = "DbOf"
	DbUf        = "DbUf"
	Db_SF       = "Db_SF"
	Ena         = "Ena"
	KOf         = "KOf"
	KUf         = "KUf"
	K_SF        = "K_SF"
	NCtl        = "NCtl"
	PMin        = "PMin"
	ReadOnly    = "ReadOnly"
	RspTms      = "RspTms"
	RspTms_SF   = "RspTms_SF"
	RvrtCtl     = "RvrtCtl"
	RvrtRem     = "RvrtRem"
	RvrtTms     = "RvrtTms"
)

type Block711Repeat struct {
	DbOf     uint32         `sunspec:"offset=0,sf=Db_SF,access=rw"`
	DbUf     uint32         `sunspec:"offset=2,sf=Db_SF,access=rw"`
	KOf      uint16         `sunspec:"offset=4,sf=K_SF,access=rw"`
	KUf      uint16         `sunspec:"offset=5,sf=K_SF,access=rw"`
	RspTms   uint32         `sunspec:"offset=6,sf=RspTms_SF,access=rw"`
	PMin     int16          `sunspec:"offset=8,access=rw"`
	ReadOnly sunspec.Enum16 `sunspec:"offset=9"`
}

type Block711 struct {
	Ena         sunspec.Enum16      `sunspec:"offset=0,access=rw"`
	AdptCtlReq  uint16              `sunspec:"offset=1,access=rw"`
	AdptCtlRslt sunspec.Enum16      `sunspec:"offset=2"`
	NCtl        uint16              `sunspec:"offset=3"`
	RvrtTms     uint32              `sunspec:"offset=4,access=rw"`
	RvrtRem     uint32              `sunspec:"offset=6"`
	RvrtCtl     uint16              `sunspec:"offset=8,access=rw"`
	Db_SF       sunspec.ScaleFactor `sunspec:"offset=9"`
	K_SF        sunspec.ScaleFactor `sunspec:"offset=10"`
	RspTms_SF   sunspec.ScaleFactor `sunspec:"offset=11"`

	Repeats []Block711Repeat
}

func (block *Block711) GetId() sunspec.ModelId {
	return ModelID
}

func init() {
	types.RegisterModel(&types.Model{
		Id:          ModelID,
		Name:        "DERFreqDroop",
		Label:       "DER Frequency Droop",
		Description: "DER Frequency Droop model.",
		Length:      22,
		Blocks: []types.Block{
			{
				Length: 12,
				Type:   types.BlockFixed,
				Points: []types.Point{
					{Id: Ena, Offset: 0, Type: typelabel.Enum16, Access: "rw", Mandatory: true, Label: "DER Frequency Droop Module Enable", Description: "DER Frequency-Watt (Frequency-Droop) control enable."},
					{Id: AdptCtlReq, Offset: 1, Type: typelabel.Uint16, Access: "rw", Mandatory: true, Label: "Set Active Control Request", Description: "Set active control. 0 = No active control."},
					{Id: AdptCtlRslt, Offset: 2, Type: typelabel.Enum16, Mandatory: true, Label: "Set Active Control Result", Description: "Result of last set active control operation."},
					{Id: NCtl, Offset: 3, Type: typelabel.Uint16, Mandatory: true, Label: "Stored Control Count", Description: "Number of stored controls supported."},
					{Id: RvrtTms, Offset: 4, Type: typelabel.Uint32, Units: "Secs", Access: "rw", Label: "Reversion Timeout", Description: "Reversion time in seconds. 0 = No reversion time."},
					{Id: RvrtRem, Offset: 6, Type: typelabel.Uint32, Units: "Secs", Label: "Reversion Time Left", Description: "Reversion time remaining in seconds."},
					{Id: RvrtCtl, Offset: 8, Type: typelabel.Uint16, Access: "rw", Label: "Reversion Control", Description: "Default control after reversion timeout."},
					{Id: Db_SF, Offset: 9, Type: typelabel.ScaleFactor, Mandatory: true, Label: "Deadband Scale Factor", Description: "Deadband scale factor."},
					{Id: K_SF, Offset: 10, Type: typelabel.ScaleFactor, Mandatory: true, Label: "Frequency Change Scale Factor", Description: "Frequency change scale factor."},
					{Id: RspTms_SF, Offset: 11, Type: typelabel.ScaleFactor, Mandatory: true, Label: "Open-Loop Scale Factor", Description: "Open loop response time scale factor."},
				},
			},
			{Name: "Ctl",
				Length: 10,
				Type:   types.BlockRepeating,
				Points: []types.Point{
					{Id: DbOf, Offset: 0, Type: typelabel.Uint32, ScaleFactor: "Db_SF", Units: "Hz", Access: "rw", Mandatory: true, Label: "Over-Frequency Deadband", Description: "The deadband value for over-frequency conditions in Hz."},
					{Id: DbUf, Offset: 2, Type: typelabel.Uint32, ScaleFactor: "Db_SF", Units: "Hz", Access: "rw", Mandatory: true, Label: "Under-Frequency Deadband", Description: "The deadband value for under-frequency conditions in Hz."},
					{Id: KOf, Offset: 4, Type: typelabel.Uint16, ScaleFactor: "K_SF", Access: "rw", Mandatory: true, Label: "Over-Frequency Change Ratio", Description: "Frequency droop per-unit frequency change for over-frequency conditions corresponding to 1 per-unit power output change."},
					{Id: KUf, Offset: 5, Type: typelabel.Uint16, ScaleFactor: "K_SF", Access: "rw", Mandatory: true, Label: "Under-Frequency Change Ratio", Description: "Frequency droop per-unit frequency change for under-frequency conditions corresponding to 1 per-unit power output change."},
					{Id: RspTms, Offset: 6, Type: typelabel.Uint32, ScaleFactor: "RspTms_SF", Units: "Secs", Access: "rw", Mandatory: true, Label: "Open-Loop Response Time", Description: "The open-loop response time in seconds."},
					{Id: PMin, Offset: 8, Type: typelabel.Int16, Units: "Pct", Access: "rw", Label: "Minimum Active Power", Description: "The minimum active power output due to DER prime mover constraints, in percent of the DER active power rating. The valid range is -100 to 100. This setting applies only to the frequency droop control."},
					{Id: ReadOnly, Offset: 9, Type: typelabel.Enum16, Mandatory: true, Label: "Control Access", Description: "Control read-write access."},
				},
			},
		}})
}
