package model701

// Code generated by ../../generators/models.go. DO NOT EDIT.
// You can regenerate it by running 'go generate ./models' from the directory above.

import (
	"github.com/andig/gosunspec"
	"github.com/andig/gosunspec/smdx"
	"github.com/andig/gosunspec/typelabel"
)

// Block701 - DER AC Measurement - DER AC measurement model.

const (
	ModelID          = 701
	ModelLabel       = "DER AC Measurement"
	ModelDescription = "DER AC measurement model."
)

const (
	A            = "A"
	ACType       = "ACType"
	AL1          = "AL1"
	AL2          = "AL2"
	AL3          = "AL3"
	A_SF         = "A_SF"
	Alrm         = "Alrm"
	ConnSt       = "ConnSt"
	Hz           = "Hz"
	Hz_SF        = "Hz_SF"
	LLV          = "LLV"
	LNV          = "LNV"
	MnAlrmInfo   = "MnAlrmInfo"
	PF           = "PF"
	PFL1         = "PFL1"
	PFL2         = "PFL2"
	PFL3         = "PFL3"
	PF_SF        = "PF_SF"
	St           = "St"
	ThrotPct     = "ThrotPct"
	ThrotSrc     = "ThrotSrc"
	TmpAmb       = "TmpAmb"
	TmpCab       = "TmpCab"
	TmpOt        = "TmpOt"
	TmpSnk       = "TmpSnk"
	TmpSw        = "TmpSw"
	TmpTrns      = "TmpTrns"
	Tmp_SF       = "Tmp_SF"
	TotVarhAbs   = "TotVarhAbs"
	TotVarhAbsL1 = "TotVarhAbsL1"
	TotVarhAbsL2 = "TotVarhAbsL2"
	TotVarhAbsL3 = "TotVarhAbsL3"
	TotVarhInj   = "TotVarhInj"
	TotVarhInjL1 = "TotVarhInjL1"
	TotVarhInjL2 = "TotVarhInjL2"
	TotVarhInjL3 = "TotVarhInjL3"
	TotVarh_SF   = "TotVarh_SF"
	TotWhAbs     = "TotWhAbs"
	TotWhAbsL1   = "TotWhAbsL1"
	TotWhAbsL2   = "TotWhAbsL2"
	TotWhAbsL3   = "TotWhAbsL3"
	TotWhInj     = "TotWhInj"
	TotWhInjL1   = "TotWhInjL1"
	TotWhInjL2   = "TotWhInjL2"
	TotWhInjL3   = "TotWhInjL3"
	TotWh_SF     = "TotWh_SF"
	VA           = "VA"
	VAL1         = "VAL1"
	VAL2         = "VAL2"
	VAL3         = "VAL3"
	VA_SF        = "VA_SF"
	VL1          = "VL1"
	VL1L2        = "VL1L2"
	VL2          = "VL2"
	VL2L3        = "VL2L3"
	VL3          = "VL3"
	VL3L1        = "VL3L1"
	V_SF         = "V_SF"
	Var          = "Var"
	VarL1        = "VarL1"
	VarL2        = "VarL2"
	VarL3        = "VarL3"
	Var_SF       = "Var_SF"
	W            = "W"
	WL1          = "WL1"
	WL2          = "WL2"
	WL3          = "WL3"
	W_SF         = "W_SF"
)

type Block701 struct {
	ACType       sunspec.Enum16      `sunspec:"offset=0,len=1,access=r"`
	St           sunspec.Enum16      `sunspec:"offset=1,len=1,access=r"`
	ConnSt       sunspec.Enum16      `sunspec:"offset=2,len=1,access=r"`
	Alrm         sunspec.Bitfield32  `sunspec:"offset=3,len=2,access=r"`
	W            int16               `sunspec:"offset=5,len=1,sf=W_SF,access=r"`
	VA           int16               `sunspec:"offset=6,len=1,sf=VA_SF,access=r"`
	Var          int16               `sunspec:"offset=7,len=1,sf=Var_SF,access=r"`
	PF           uint16              `sunspec:"offset=8,len=1,sf=PF_SF,access=r"`
	A            int16               `sunspec:"offset=9,len=1,sf=A_SF,access=r"`
	LLV          int16               `sunspec:"offset=10,len=1,sf=V_SF,access=r"`
	LNV          int16               `sunspec:"offset=11,len=1,sf=V_SF,access=r"`
	Hz           uint32              `sunspec:"offset=12,len=2,sf=Hz_SF,access=r"`
	TotWhInj     uint64              `sunspec:"offset=14,len=4,sf=TotWh_SF,access=r"`
	TotWhAbs     uint64              `sunspec:"offset=18,len=4,sf=TotWh_SF,access=r"`
	TotVarhInj   uint64              `sunspec:"offset=22,len=4,sf=TotVarh_SF,access=r"`
	TotVarhAbs   uint64              `sunspec:"offset=26,len=4,sf=TotVarh_SF,access=r"`
	TmpAmb       int16               `sunspec:"offset=30,len=1,sf=Tmp_SF,access=r"`
	TmpCab       int16               `sunspec:"offset=31,len=1,sf=Tmp_SF,access=r"`
	TmpSnk       int16               `sunspec:"offset=32,len=1,sf=Tmp_SF,access=r"`
	TmpTrns      int16               `sunspec:"offset=33,len=1,sf=Tmp_SF,access=r"`
	TmpSw        int16               `sunspec:"offset=34,len=1,sf=Tmp_SF,access=r"`
	TmpOt        int16               `sunspec:"offset=35,len=1,sf=Tmp_SF,access=r"`
	WL1          int16               `sunspec:"offset=36,len=1,sf=W_SF,access=r"`
	VAL1         int16               `sunspec:"offset=37,len=1,sf=VA_SF,access=r"`
	VarL1        int16               `sunspec:"offset=38,len=1,sf=Var_SF,access=r"`
	PFL1         uint16              `sunspec:"offset=39,len=1,sf=PF_SF,access=r"`
	AL1          int16               `sunspec:"offset=40,len=1,sf=A_SF,access=r"`
	VL1L2        int16               `sunspec:"offset=41,len=1,sf=V_SF,access=r"`
	VL1          int16               `sunspec:"offset=42,len=1,sf=V_SF,access=r"`
	TotWhInjL1   uint64              `sunspec:"offset=43,len=4,sf=TotWh_SF,access=r"`
	TotWhAbsL1   uint64              `sunspec:"offset=47,len=4,sf=TotWh_SF,access=r"`
	TotVarhInjL1 uint64              `sunspec:"offset=51,len=4,sf=TotVarh_SF,access=r"`
	TotVarhAbsL1 uint64              `sunspec:"offset=55,len=4,sf=TotVarh_SF,access=r"`
	WL2          int16               `sunspec:"offset=59,len=1,sf=W_SF,access=r"`
	VAL2         int16               `sunspec:"offset=60,len=1,sf=VA_SF,access=r"`
	VarL2        int16               `sunspec:"offset=61,len=1,sf=Var_SF,access=r"`
	PFL2         uint16              `sunspec:"offset=62,len=1,sf=PF_SF,access=r"`
	AL2          int16               `sunspec:"offset=63,len=1,sf=A_SF,access=r"`
	VL2L3        int16               `sunspec:"offset=64,len=1,sf=V_SF,access=r"`
	VL2          int16               `sunspec:"offset=65,len=1,sf=V_SF,access=r"`
	TotWhInjL2   uint64              `sunspec:"offset=66,len=4,sf=TotWh_SF,access=r"`
	TotWhAbsL2   uint64              `sunspec:"offset=70,len=4,sf=TotWh_SF,access=r"`
	TotVarhInjL2 uint64              `sunspec:"offset=74,len=4,sf=TotVarh_SF,access=r"`
	TotVarhAbsL2 uint64              `sunspec:"offset=78,len=4,sf=TotVarh_SF,access=r"`
	WL3          int16               `sunspec:"offset=82,len=1,sf=W_SF,access=r"`
	VAL3         int16               `sunspec:"offset=83,len=1,sf=VA_SF,access=r"`
	VarL3        int16               `sunspec:"offset=84,len=1,sf=Var_SF,access=r"`
	PFL3         uint16              `sunspec:"offset=85,len=1,sf=PF_SF,access=r"`
	AL3          int16               `sunspec:"offset=86,len=1,sf=A_SF,access=r"`
	VL3L1        int16               `sunspec:"offset=87,len=1,sf=V_SF,access=r"`
	VL3          int16               `sunspec:"offset=88,len=1,sf=V_SF,access=r"`
	TotWhInjL3   uint64              `sunspec:"offset=89,len=4,sf=TotWh_SF,access=r"`
	TotWhAbsL3   uint64              `sunspec:"offset=93,len=4,sf=TotWh_SF,access=r"`
	TotVarhInjL3 uint64              `sunspec:"offset=97,len=4,sf=TotVarh_SF,access=r"`
	TotVarhAbsL3 uint64              `sunspec:"offset=101,len=4,sf=TotVarh_SF,access=r"`
	ThrotPct     uint16              `sunspec:"offset=105,len=1,access=r"`
	ThrotSrc     sunspec.Bitfield32  `sunspec:"offset=106,len=2,access=r"`
	A_SF         sunspec.ScaleFactor `sunspec:"offset=108,len=1,access=r"`
	V_SF         sunspec.ScaleFactor `sunspec:"offset=109,len=1,access=r"`
	Hz_SF        sunspec.ScaleFactor `sunspec:"offset=110,len=1,access=r"`
	W_SF         sunspec.ScaleFactor `sunspec:"offset=111,len=1,access=r"`
	PF_SF        sunspec.ScaleFactor `sunspec:"offset=112,len=1,access=r"`
	VA_SF        sunspec.ScaleFactor `sunspec:"offset=113,len=1,access=r"`
	Var_SF       sunspec.ScaleFactor `sunspec:"offset=114,len=1,access=r"`
	TotWh_SF     sunspec.ScaleFactor `sunspec:"offset=115,len=1,access=r"`
	TotVarh_SF   sunspec.ScaleFactor `sunspec:"offset=116,len=1,access=r"`
	Tmp_SF       sunspec.ScaleFactor `sunspec:"offset=117,len=1,access=r"`
	MnAlrmInfo   string              `sunspec:"offset=118,len=32,access=r"`
}

func (block *Block701) GetId() sunspec.ModelId {
	return ModelID
}

func init() {
	smdx.RegisterModel(&smdx.ModelElement{
		Id:     ModelID,
		Name:   "DERMeasureAC",
		Length: 150,
		Blocks: []smdx.BlockElement{
			{
				Length: 150,
				Points: []smdx.PointElement{
					{Id: ACType, Offset: 0, Type: typelabel.Enum16, Access: "r", Length: 1, Label: "AC Wiring Type", Description: "AC wiring type."},
					{Id: St, Offset: 1, Type: typelabel.Enum16, Access: "r", Length: 1, Label: "Operating State", Description: "Operating state of the DER."},
					{Id: ConnSt, Offset: 2, Type: typelabel.Enum16, Access: "r", Length: 1, Label: "Grid Connection State", Description: "Grid connection state of the DER."},
					{Id: Alrm, Offset: 3, Type: typelabel.Bitfield32, Access: "r", Length: 2, Label: "Alarm Bitfield", Description: "Active alarms for the DER."},
					{Id: W, Offset: 5, Type: typelabel.Int16, ScaleFactor: "W_SF", Units: "W", Access: "r", Length: 1, Label: "Active Power", Description: "Total active power."},
					{Id: VA, Offset: 6, Type: typelabel.Int16, ScaleFactor: "VA_SF", Units: "VA", Access: "r", Length: 1, Label: "Apparent Power", Description: "Total apparent power."},
					{Id: Var, Offset: 7, Type: typelabel.Int16, ScaleFactor: "Var_SF", Units: "Var", Access: "r", Length: 1, Label: "Reactive Power", Description: "Total reactive power."},
					{Id: PF, Offset: 8, Type: typelabel.Uint16, ScaleFactor: "PF_SF", Access: "r", Length: 1, Label: "Power Factor", Description: "Power factor."},
					{Id: A, Offset: 9, Type: typelabel.Int16, ScaleFactor: "A_SF", Units: "A", Access: "r", Length: 1, Label: "Total AC Current", Description: "Total AC current."},
					{Id: LLV, Offset: 10, Type: typelabel.Int16, ScaleFactor: "V_SF", Units: "V", Access: "r", Length: 1, Label: "Voltage LL", Description: "Line to line AC voltage as an average of active phases."},
					{Id: LNV, Offset: 11, Type: typelabel.Int16, ScaleFactor: "V_SF", Units: "V", Access: "r", Length: 1, Label: "Voltage LN", Description: "Line to neutral AC voltage as an average of active phases."},
					{Id: Hz, Offset: 12, Type: typelabel.Uint32, ScaleFactor: "Hz_SF", Units: "Hz", Access: "r", Length: 2, Label: "Frequency", Description: "AC frequency."},
					{Id: TotWhInj, Offset: 14, Type: typelabel.Uint64, ScaleFactor: "TotWh_SF", Units: "Wh", Access: "r", Length: 4, Label: "Total Energy Injected", Description: "Total active energy injected (Quadrants 1 & 4)."},
					{Id: TotWhAbs, Offset: 18, Type: typelabel.Uint64, ScaleFactor: "TotWh_SF", Units: "Wh", Access: "r", Length: 4, Label: "Total Energy Absorbed", Description: "Total active energy absorbed (Quadrants 2 & 3)."},
					{Id: TotVarhInj, Offset: 22, Type: typelabel.Uint64, ScaleFactor: "TotVarh_SF", Units: "Varh", Access: "r", Length: 4, Label: "Total Reactive Energy Inj", Description: "Total reactive energy injected (Quadrants 1 & 2)."},
					{Id: TotVarhAbs, Offset: 26, Type: typelabel.Uint64, ScaleFactor: "TotVarh_SF", Units: "Varh", Access: "r", Length: 4, Label: "Total Reactive Energy Abs", Description: "Total reactive energy absorbed (Quadrants 3 & 4)."},
					{Id: TmpAmb, Offset: 30, Type: typelabel.Int16, ScaleFactor: "Tmp_SF", Units: "C", Access: "r", Length: 1, Label: "Ambient Temperature", Description: "Ambient temperature."},
					{Id: TmpCab, Offset: 31, Type: typelabel.Int16, ScaleFactor: "Tmp_SF", Units: "C", Access: "r", Length: 1, Label: "Cabinet Temperature", Description: "Cabinet temperature."},
					{Id: TmpSnk, Offset: 32, Type: typelabel.Int16, ScaleFactor: "Tmp_SF", Units: "C", Access: "r", Length: 1, Label: "Heat Sink Temperature", Description: "Heat sink temperature."},
					{Id: TmpTrns, Offset: 33, Type: typelabel.Int16, ScaleFactor: "Tmp_SF", Units: "C", Access: "r", Length: 1, Label: "Transformer Temperature", Description: "Transformer temperature."},
					{Id: TmpSw, Offset: 34, Type: typelabel.Int16, ScaleFactor: "Tmp_SF", Units: "C", Access: "r", Length: 1, Label: "IGBT/MOSFET Temperature", Description: "IGBT/MOSFET temperature."},
					{Id: TmpOt, Offset: 35, Type: typelabel.Int16, ScaleFactor: "Tmp_SF", Units: "C", Access: "r", Length: 1, Label: "Other Temperature", Description: "Other temperature."},
					{Id: WL1, Offset: 36, Type: typelabel.Int16, ScaleFactor: "W_SF", Units: "W", Access: "r", Length: 1, Label: "Watts L1", Description: "Active power L1."},
					{Id: VAL1, Offset: 37, Type: typelabel.Int16, ScaleFactor: "VA_SF", Units: "VA", Access: "r", Length: 1, Label: "VA L1", Description: "Apparent power L1."},
					{Id: VarL1, Offset: 38, Type: typelabel.Int16, ScaleFactor: "Var_SF", Units: "Var", Access: "r", Length: 1, Label: "Var L1", Description: "Reactive power L1."},
					{Id: PFL1, Offset: 39, Type: typelabel.Uint16, ScaleFactor: "PF_SF", Access: "r", Length: 1, Label: "PF L1", Description: "Power factor phase L1."},
					{Id: AL1, Offset: 40, Type: typelabel.Int16, ScaleFactor: "A_SF", Units: "A", Access: "r", Length: 1, Label: "Amps L1", Description: "Current phase L1."},
					{Id: VL1L2, Offset: 41, Type: typelabel.Int16, ScaleFactor: "V_SF", Units: "V", Access: "r", Length: 1, Label: "Phase Voltage L1-L2", Description: "Phase voltage L1-L2."},
					{Id: VL1, Offset: 42, Type: typelabel.Int16, ScaleFactor: "V_SF", Units: "V", Access: "r", Length: 1, Label: "Phase Voltage L1-N", Description: "Phase voltage L1-N."},
					{Id: TotWhInjL1, Offset: 43, Type: typelabel.Uint64, ScaleFactor: "TotWh_SF", Units: "Wh", Access: "r", Length: 4, Label: "Total Watt-Hours Inj L1", Description: "Total active energy injected L1."},
					{Id: TotWhAbsL1, Offset: 47, Type: typelabel.Uint64, ScaleFactor: "TotWh_SF", Units: "Wh", Access: "r", Length: 4, Label: "Total Watt-Hours Abs L1", Description: "Total active energy absorbed L1."},
					{Id: TotVarhInjL1, Offset: 51, Type: typelabel.Uint64, ScaleFactor: "TotVarh_SF", Units: "Varh", Access: "r", Length: 4, Label: "Total Var-Hours Inj L1", Description: "Total reactive energy injected L1."},
					{Id: TotVarhAbsL1, Offset: 55, Type: typelabel.Uint64, ScaleFactor: "TotVarh_SF", Units: "Varh", Access: "r", Length: 4, Label: "Total Var-Hours Abs L1", Description: "Total reactive energy absorbed L1."},
					{Id: WL2, Offset: 59, Type: typelabel.Int16, ScaleFactor: "W_SF", Units: "W", Access: "r", Length: 1, Label: "Watts L2", Description: "Active power L2."},
					{Id: VAL2, Offset: 60, Type: typelabel.Int16, ScaleFactor: "VA_SF", Units: "VA", Access: "r", Length: 1, Label: "VA L2", Description: "Apparent power L2."},
					{Id: VarL2, Offset: 61, Type: typelabel.Int16, ScaleFactor: "Var_SF", Units: "Var", Access: "r", Length: 1, Label: "Var L2", Description: "Reactive power L2."},
					{Id: PFL2, Offset: 62, Type: typelabel.Uint16, ScaleFactor: "PF_SF", Access: "r", Length: 1, Label: "PF L2", Description: "Power factor L2."},
					{Id: AL2, Offset: 63, Type: typelabel.Int16, ScaleFactor: "A_SF", Units: "A", Access: "r", Length: 1, Label: "Amps L2", Description: "Current L2."},
					{Id: VL2L3, Offset: 64, Type: typelabel.Int16, ScaleFactor: "V_SF", Units: "V", Access: "r", Length: 1, Label: "Phase Voltage L2-L3", Description: "Phase voltage L2-L3."},
					{Id: VL2, Offset: 65, Type: typelabel.Int16, ScaleFactor: "V_SF", Units: "V", Access: "r", Length: 1, Label: "Phase Voltage L2-N", Description: "Phase voltage L2-N."},
					{Id: TotWhInjL2, Offset: 66, Type: typelabel.Uint64, ScaleFactor: "TotWh_SF", Units: "Wh", Access: "r", Length: 4, Label: "Total Watt-Hours Inj L2", Description: "Total active energy injected L2."},
					{Id: TotWhAbsL2, Offset: 70, Type: typelabel.Uint64, ScaleFactor: "TotWh_SF", Units: "Wh", Access: "r", Length: 4, Label: "Total Watt-Hours Abs L2", Description: "Total active energy absorbed L2."},
					{Id: TotVarhInjL2, Offset: 74, Type: typelabel.Uint64, ScaleFactor: "TotVarh_SF", Units: "Varh", Access: "r", Length: 4, Label: "Total Var-Hours Inj L2", Description: "Total reactive energy injected L2."},
					{Id: TotVarhAbsL2, Offset: 78, Type: typelabel.Uint64, ScaleFactor: "TotVarh_SF", Units: "Varh", Access: "r", Length: 4, Label: "Total Var-Hours Abs L2", Description: "Total reactive energy absorbed L2."},
					{Id: WL3, Offset: 82, Type: typelabel.Int16, ScaleFactor: "W_SF", Units: "W", Access: "r", Length: 1, Label: "Watts L3", Description: "Active power L3."},
					{Id: VAL3, Offset: 83, Type: typelabel.Int16, ScaleFactor: "VA_SF", Units: "VA", Access: "r", Length: 1, Label: "VA L3", Description: "Apparent power L3."},
					{Id: VarL3, Offset: 84, Type: typelabel.Int16, ScaleFactor: "Var_SF", Units: "Var", Access: "r", Length: 1, Label: "Var L3", Description: "Reactive power L3."},
					{Id: PFL3, Offset: 85, Type: typelabel.Uint16, ScaleFactor: "PF_SF", Access: "r", Length: 1, Label: "PF L3", Description: "Power factor L3."},
					{Id: AL3, Offset: 86, Type: typelabel.Int16, ScaleFactor: "A_SF", Units: "A", Access: "r", Length: 1, Label: "Amps L3", Description: "Current L3."},
					{Id: VL3L1, Offset: 87, Type: typelabel.Int16, ScaleFactor: "V_SF", Units: "V", Access: "r", Length: 1, Label: "Phase Voltage L3-L1", Description: "Phase voltage L3-L1."},
					{Id: VL3, Offset: 88, Type: typelabel.Int16, ScaleFactor: "V_SF", Units: "V", Access: "r", Length: 1, Label: "Phase Voltage L3-N", Description: "Phase voltage L3-N."},
					{Id: TotWhInjL3, Offset: 89, Type: typelabel.Uint64, ScaleFactor: "TotWh_SF", Units: "Wh", Access: "r", Length: 4, Label: "Total Watt-Hours Inj L3", Description: "Total active energy injected L3."},
					{Id: TotWhAbsL3, Offset: 93, Type: typelabel.Uint64, ScaleFactor: "TotWh_SF", Units: "Wh", Access: "r", Length: 4, Label: "Total Watt-Hours Abs L3", Description: "Total active energy absorbed L3."},
					{Id: TotVarhInjL3, Offset: 97, Type: typelabel.Uint64, ScaleFactor: "TotVarh_SF", Units: "Varh", Access: "r", Length: 4, Label: "Total Var-Hours Inj L3", Description: "Total reactive energy injected L3."},
					{Id: TotVarhAbsL3, Offset: 101, Type: typelabel.Uint64, ScaleFactor: "TotVarh_SF", Units: "Varh", Access: "r", Length: 4, Label: "Total Var-Hours Abs L3", Description: "Total reactive energy absorbed L3."},
					{Id: ThrotPct, Offset: 105, Type: typelabel.Uint16, Units: "Pct", Access: "r", Length: 1, Label: "Throttling In Pct", Description: "Throttling in Pct of maximum active power."},
					{Id: ThrotSrc, Offset: 106, Type: typelabel.Bitfield32, Access: "r", Length: 2, Label: "Throttle Source Information", Description: "Active throttling source."},
					{Id: A_SF, Offset: 108, Type: typelabel.ScaleFactor, Access: "r", Length: 1, Label: "Current Scale Factor", Description: "Current scale factor."},
					{Id: V_SF, Offset: 109, Type: typelabel.ScaleFactor, Access: "r", Length: 1, Label: "Voltage Scale Factor", Description: "Voltage scale factor."},
					{Id: Hz_SF, Offset: 110, Type: typelabel.ScaleFactor, Access: "r", Length: 1, Label: "Frequency Scale Factor", Description: "Frequency scale factor."},
					{Id: W_SF, Offset: 111, Type: typelabel.ScaleFactor, Access: "r", Length: 1, Label: "Active Power Scale Factor", Description: "Active power scale factor."},
					{Id: PF_SF, Offset: 112, Type: typelabel.ScaleFactor, Access: "r", Length: 1, Label: "Power Factor Scale Factor", Description: "Power factor scale factor."},
					{Id: VA_SF, Offset: 113, Type: typelabel.ScaleFactor, Access: "r", Length: 1, Label: "Apparent Power Scale Factor", Description: "Apparent power scale factor."},
					{Id: Var_SF, Offset: 114, Type: typelabel.ScaleFactor, Access: "r", Length: 1, Label: "Reactive Power Scale Factor", Description: "Reactive power scale factor."},
					{Id: TotWh_SF, Offset: 115, Type: typelabel.ScaleFactor, Access: "r", Length: 1, Label: "Active Energy Scale Factor", Description: "Active energy scale factor."},
					{Id: TotVarh_SF, Offset: 116, Type: typelabel.ScaleFactor, Access: "r", Length: 1, Label: "Reactive Energy Scale Factor", Description: "Reactive energy scale factor."},
					{Id: Tmp_SF, Offset: 117, Type: typelabel.ScaleFactor, Access: "r", Length: 1, Label: "Temperature Scale Factor", Description: "Temperature scale factor."},
					{Id: MnAlrmInfo, Offset: 118, Type: typelabel.String, Access: "r", Length: 32, Label: "Manufacturer Alarm Info", Description: "Manufacturer alarm information. Valid if MANUFACTURER_ALRM indication is active."},
				},
			},
		}})
}
