package model122

// Code generated by ../../generators/json/models.go. DO NOT EDIT.
// You can regenerate it by running 'make spec' from the project root.

import (
	"github.com/andig/gosunspec"
	"github.com/andig/gosunspec/typelabel"
	"github.com/andig/gosunspec/types"
)

// Block122 - Measurements_Status - Inverter Controls Extended Measurements and Status

const (
	ModelID          = 122
	ModelLabel       = "Measurements_Status"
	ModelDescription = "Inverter Controls Extended Measurements and Status "
)

const (
	ActVAh      = "ActVAh"
	ActVArhQ1   = "ActVArhQ1"
	ActVArhQ2   = "ActVArhQ2"
	ActVArhQ3   = "ActVArhQ3"
	ActVArhQ4   = "ActVArhQ4"
	ActWh       = "ActWh"
	ECPConn     = "ECPConn"
	PVConn      = "PVConn"
	Ris         = "Ris"
	Ris_SF      = "Ris_SF"
	RtSt        = "RtSt"
	StActCtl    = "StActCtl"
	StSetLimMsk = "StSetLimMsk"
	StorConn    = "StorConn"
	TmSrc       = "TmSrc"
	Tms         = "Tms"
	VArAval     = "VArAval"
	VArAval_SF  = "VArAval_SF"
	WAval       = "WAval"
	WAval_SF    = "WAval_SF"
)

type Block122 struct {
	PVConn      sunspec.Bitfield16  `sunspec:"offset=0"`
	StorConn    sunspec.Bitfield16  `sunspec:"offset=1"`
	ECPConn     sunspec.Bitfield16  `sunspec:"offset=2"`
	ActWh       sunspec.Acc64       `sunspec:"offset=3"`
	ActVAh      sunspec.Acc64       `sunspec:"offset=7"`
	ActVArhQ1   sunspec.Acc64       `sunspec:"offset=11"`
	ActVArhQ2   sunspec.Acc64       `sunspec:"offset=15"`
	ActVArhQ3   sunspec.Acc64       `sunspec:"offset=19"`
	ActVArhQ4   sunspec.Acc64       `sunspec:"offset=23"`
	VArAval     int16               `sunspec:"offset=27,sf=VArAval_SF"`
	VArAval_SF  sunspec.ScaleFactor `sunspec:"offset=28"`
	WAval       uint16              `sunspec:"offset=29,sf=WAval_SF"`
	WAval_SF    sunspec.ScaleFactor `sunspec:"offset=30"`
	StSetLimMsk sunspec.Bitfield32  `sunspec:"offset=31"`
	StActCtl    sunspec.Bitfield32  `sunspec:"offset=33"`
	TmSrc       string              `sunspec:"offset=35,len=4"`
	Tms         uint32              `sunspec:"offset=39"`
	RtSt        sunspec.Bitfield16  `sunspec:"offset=41"`
	Ris         uint16              `sunspec:"offset=42,sf=Ris_SF"`
	Ris_SF      sunspec.ScaleFactor `sunspec:"offset=43"`
}

func (block *Block122) GetId() sunspec.ModelId {
	return ModelID
}

func init() {
	types.RegisterModel(&types.Model{
		Id:          ModelID,
		Name:        "status",
		Label:       "Measurements_Status",
		Description: "Inverter Controls Extended Measurements and Status ",
		Length:      44,
		Blocks: []types.Block{
			{
				Length: 44,
				Type:   types.BlockFixed,
				Points: []types.Point{
					{Id: PVConn, Offset: 0, Type: typelabel.Bitfield16, Mandatory: true, Label: "PVConn", Description: "PV inverter present/available status."},
					{Id: StorConn, Offset: 1, Type: typelabel.Bitfield16, Mandatory: true, Label: "StorConn", Description: "Storage inverter present/available status."},
					{Id: ECPConn, Offset: 2, Type: typelabel.Bitfield16, Mandatory: true, Label: "ECPConn", Description: "ECP connection status: disconnected=0 connected=1."},
					{Id: ActWh, Offset: 3, Type: typelabel.Acc64, Units: "Wh", Label: "ActWh", Description: "AC lifetime active (real) energy output."},
					{Id: ActVAh, Offset: 7, Type: typelabel.Acc64, Units: "VAh", Label: "ActVAh", Description: "AC lifetime apparent energy output."},
					{Id: ActVArhQ1, Offset: 11, Type: typelabel.Acc64, Units: "varh", Label: "ActVArhQ1", Description: "AC lifetime reactive energy output in quadrant 1."},
					{Id: ActVArhQ2, Offset: 15, Type: typelabel.Acc64, Units: "varh", Label: "ActVArhQ2", Description: "AC lifetime reactive energy output in quadrant 2."},
					{Id: ActVArhQ3, Offset: 19, Type: typelabel.Acc64, Units: "varh", Label: "ActVArhQ3", Description: "AC lifetime negative energy output in quadrant 3."},
					{Id: ActVArhQ4, Offset: 23, Type: typelabel.Acc64, Units: "varh", Label: "ActVArhQ4", Description: "AC lifetime reactive energy output in quadrant 4."},
					{Id: VArAval, Offset: 27, Type: typelabel.Int16, ScaleFactor: "VArAval_SF", Units: "var", Label: "VArAval", Description: "Amount of VARs available without impacting watts output."},
					{Id: VArAval_SF, Offset: 28, Type: typelabel.ScaleFactor, Label: "VArAval_SF", Description: "Scale factor for available VARs."},
					{Id: WAval, Offset: 29, Type: typelabel.Uint16, ScaleFactor: "WAval_SF", Units: "var", Label: "WAval", Description: "Amount of Watts available."},
					{Id: WAval_SF, Offset: 30, Type: typelabel.ScaleFactor, Label: "WAval_SF", Description: "Scale factor for available Watts."},
					{Id: StSetLimMsk, Offset: 31, Type: typelabel.Bitfield32, Label: "StSetLimMsk", Description: "Setpoint limit(s) reached."},
					{Id: StActCtl, Offset: 33, Type: typelabel.Bitfield32, Label: "StActCtl", Description: "Which inverter controls are currently active."},
					{Id: TmSrc, Offset: 35, Type: typelabel.String, Length: 4, Label: "TmSrc", Description: "Source of time synchronization."},
					{Id: Tms, Offset: 39, Type: typelabel.Uint32, Units: "Secs", Label: "Tms", Description: "Seconds since 01-01-2000 00:00 UTC"},
					{Id: RtSt, Offset: 41, Type: typelabel.Bitfield16, Label: "RtSt", Description: "Active ride-through status."},
					{Id: Ris, Offset: 42, Type: typelabel.Uint16, ScaleFactor: "Ris_SF", Units: "ohms", Label: "Ris", Description: "Isolation resistance."},
					{Id: Ris_SF, Offset: 43, Type: typelabel.ScaleFactor, Label: "Ris_SF", Description: "Scale factor for isolation resistance."},
				},
			},
		}})
}
