package model64001

// Code generated by ../../generators/models.go. DO NOT EDIT.
// You can regenerate it by running 'go generate ./models' from the directory above.

import (
	"github.com/andig/gosunspec"
	"github.com/andig/gosunspec/smdx"
	"github.com/andig/gosunspec/typelabel"
)

// Block64001 - Veris Status and Configuration -

const (
	ModelID          = 64001
	ModelLabel       = "Veris Status and Configuration"
	ModelDescription = ""
)

const (
	Boots    = "Boots"
	Cmd      = "Cmd"
	Config   = "Config"
	HWRev    = "HWRev"
	LEDblink = "LEDblink"
	LEDon    = "LEDon"
	Loc      = "Loc"
	OSFWRev  = "OSFWRev"
	ProdRev  = "ProdRev"
	RSFWRev  = "RSFWRev"
	Reserved = "Reserved"
	S1Addr   = "S1Addr"
	S1ID     = "S1ID"
	S1OSVer  = "S1OSVer"
	S1Serial = "S1Serial"
	S1Ver    = "S1Ver"
	S2Addr   = "S2Addr"
	S2ID     = "S2ID"
	S2OSVer  = "S2OSVer"
	S2Serial = "S2Serial"
	S2Ver    = "S2Ver"
	S3Addr   = "S3Addr"
	S3ID     = "S3ID"
	S3OSVer  = "S3OSVer"
	S3Serial = "S3Serial"
	S3Ver    = "S3Ver"
	S4Addr   = "S4Addr"
	S4ID     = "S4ID"
	S4OSVer  = "S4OSVer"
	S4Serial = "S4Serial"
	S4Ver    = "S4Ver"
	Sensors  = "Sensors"
	Status   = "Status"
	Switch   = "Switch"
	Talking  = "Talking"
)

type Block64001 struct {
	Cmd      sunspec.Enum16     `sunspec:"offset=0,len=1,access=rw"`
	HWRev    uint16             `sunspec:"offset=1,len=1,access=r"`
	RSFWRev  uint16             `sunspec:"offset=2,len=1,access=r"`
	OSFWRev  uint16             `sunspec:"offset=3,len=1,access=r"`
	ProdRev  string             `sunspec:"offset=4,len=2,access=r"`
	Boots    uint16             `sunspec:"offset=6,len=1,access=r"`
	Switch   sunspec.Bitfield16 `sunspec:"offset=7,len=1,access=r"`
	Sensors  uint16             `sunspec:"offset=8,len=1,access=r"`
	Talking  uint16             `sunspec:"offset=9,len=1,access=r"`
	Status   sunspec.Bitfield16 `sunspec:"offset=10,len=1,access=r"`
	Config   sunspec.Bitfield16 `sunspec:"offset=11,len=1,access=r"`
	LEDblink uint16             `sunspec:"offset=12,len=1,access=r"`
	LEDon    uint16             `sunspec:"offset=13,len=1,access=r"`
	Reserved uint16             `sunspec:"offset=14,len=1,access=r"`
	Loc      string             `sunspec:"offset=15,len=16,access=r"`
	S1ID     sunspec.Enum16     `sunspec:"offset=31,len=1,access=r"`
	S1Addr   uint16             `sunspec:"offset=32,len=1,access=r"`
	S1OSVer  uint16             `sunspec:"offset=33,len=1,access=r"`
	S1Ver    string             `sunspec:"offset=34,len=2,access=r"`
	S1Serial string             `sunspec:"offset=36,len=5,access=r"`
	S2ID     sunspec.Enum16     `sunspec:"offset=41,len=1,access=r"`
	S2Addr   uint16             `sunspec:"offset=42,len=1,access=r"`
	S2OSVer  uint16             `sunspec:"offset=43,len=1,access=r"`
	S2Ver    string             `sunspec:"offset=44,len=2,access=r"`
	S2Serial string             `sunspec:"offset=46,len=5,access=r"`
	S3ID     sunspec.Enum16     `sunspec:"offset=51,len=1,access=r"`
	S3Addr   uint16             `sunspec:"offset=52,len=1,access=r"`
	S3OSVer  uint16             `sunspec:"offset=53,len=1,access=r"`
	S3Ver    string             `sunspec:"offset=54,len=2,access=r"`
	S3Serial string             `sunspec:"offset=56,len=5,access=r"`
	S4ID     sunspec.Enum16     `sunspec:"offset=61,len=1,access=r"`
	S4Addr   uint16             `sunspec:"offset=62,len=1,access=r"`
	S4OSVer  uint16             `sunspec:"offset=63,len=1,access=r"`
	S4Ver    string             `sunspec:"offset=64,len=2,access=r"`
	S4Serial string             `sunspec:"offset=66,len=5,access=r"`
}

func (block *Block64001) GetId() sunspec.ModelId {
	return ModelID
}

func init() {
	smdx.RegisterModel(&smdx.ModelElement{
		Id:     ModelID,
		Name:   "model_64001",
		Length: 71,
		Blocks: []smdx.BlockElement{
			{
				Length: 71,
				Points: []smdx.PointElement{
					{Id: Cmd, Offset: 0, Type: typelabel.Enum16, Access: "rw", Length: 1, Label: "Command Code", Description: ""},
					{Id: HWRev, Offset: 1, Type: typelabel.Uint16, Access: "r", Length: 1, Label: "Hardware Revision", Description: ""},
					{Id: RSFWRev, Offset: 2, Type: typelabel.Uint16, Access: "r", Length: 1, Label: "RS FW Revision", Description: ""},
					{Id: OSFWRev, Offset: 3, Type: typelabel.Uint16, Access: "r", Length: 1, Label: "OS FW Revision", Description: ""},
					{Id: ProdRev, Offset: 4, Type: typelabel.String, Access: "r", Length: 2, Label: "Product Revision", Description: ""},
					{Id: Boots, Offset: 6, Type: typelabel.Uint16, Access: "r", Length: 1, Label: "Boot Count", Description: ""},
					{Id: Switch, Offset: 7, Type: typelabel.Bitfield16, Access: "r", Length: 1, Label: "DIP Switches", Description: ""},
					{Id: Sensors, Offset: 8, Type: typelabel.Uint16, Access: "r", Length: 1, Label: "Num Detected Sensors", Description: ""},
					{Id: Talking, Offset: 9, Type: typelabel.Uint16, Access: "r", Length: 1, Label: "Num Communicating Sensors", Description: ""},
					{Id: Status, Offset: 10, Type: typelabel.Bitfield16, Access: "r", Length: 1, Label: "System Status", Description: ""},
					{Id: Config, Offset: 11, Type: typelabel.Bitfield16, Access: "r", Length: 1, Label: "System Configuration", Description: ""},
					{Id: LEDblink, Offset: 12, Type: typelabel.Uint16, Units: "Pct", Access: "r", Length: 1, Label: "LED Blink Threshold", Description: ""},
					{Id: LEDon, Offset: 13, Type: typelabel.Uint16, Units: "Pct", Access: "r", Length: 1, Label: "LED On Threshold", Description: ""},
					{Id: Reserved, Offset: 14, Type: typelabel.Uint16, Access: "r", Length: 1},
					{Id: Loc, Offset: 15, Type: typelabel.String, Access: "r", Length: 16, Label: "Location String", Description: ""},
					{Id: S1ID, Offset: 31, Type: typelabel.Enum16, Access: "r", Length: 1, Label: "Sensor 1 Unit ID", Description: ""},
					{Id: S1Addr, Offset: 32, Type: typelabel.Uint16, Access: "r", Length: 1, Label: "Sensor 1 Address", Description: ""},
					{Id: S1OSVer, Offset: 33, Type: typelabel.Uint16, Access: "r", Length: 1, Label: "Sensor 1 OS Version", Description: ""},
					{Id: S1Ver, Offset: 34, Type: typelabel.String, Access: "r", Length: 2, Label: "Sensor 1 Product Version", Description: ""},
					{Id: S1Serial, Offset: 36, Type: typelabel.String, Access: "r", Length: 5, Label: "Sensor 1 Serial Num", Description: ""},
					{Id: S2ID, Offset: 41, Type: typelabel.Enum16, Access: "r", Length: 1, Label: "Sensor 2 Unit ID", Description: ""},
					{Id: S2Addr, Offset: 42, Type: typelabel.Uint16, Access: "r", Length: 1, Label: "Sensor 2 Address", Description: ""},
					{Id: S2OSVer, Offset: 43, Type: typelabel.Uint16, Access: "r", Length: 1, Label: "Sensor 2 OS Version", Description: ""},
					{Id: S2Ver, Offset: 44, Type: typelabel.String, Access: "r", Length: 2, Label: "Sensor 2 Product Version", Description: ""},
					{Id: S2Serial, Offset: 46, Type: typelabel.String, Access: "r", Length: 5, Label: "Sensor 2 Serial Num", Description: ""},
					{Id: S3ID, Offset: 51, Type: typelabel.Enum16, Access: "r", Length: 1, Label: "Sensor 3 Unit ID", Description: ""},
					{Id: S3Addr, Offset: 52, Type: typelabel.Uint16, Access: "r", Length: 1, Label: "Sensor 3 Address", Description: ""},
					{Id: S3OSVer, Offset: 53, Type: typelabel.Uint16, Access: "r", Length: 1, Label: "Sensor 3 OS Version", Description: ""},
					{Id: S3Ver, Offset: 54, Type: typelabel.String, Access: "r", Length: 2, Label: "Sensor 3 Product Version", Description: ""},
					{Id: S3Serial, Offset: 56, Type: typelabel.String, Access: "r", Length: 5, Label: "Sensor 3 Serial Num", Description: ""},
					{Id: S4ID, Offset: 61, Type: typelabel.Enum16, Access: "r", Length: 1, Label: "Sensor 4 Unit ID", Description: ""},
					{Id: S4Addr, Offset: 62, Type: typelabel.Uint16, Access: "r", Length: 1, Label: "Sensor 4 Address", Description: ""},
					{Id: S4OSVer, Offset: 63, Type: typelabel.Uint16, Access: "r", Length: 1, Label: "Sensor 4 OS Version", Description: ""},
					{Id: S4Ver, Offset: 64, Type: typelabel.String, Access: "r", Length: 2, Label: "Sensor 4 Product Version", Description: ""},
					{Id: S4Serial, Offset: 66, Type: typelabel.String, Access: "r", Length: 5, Label: "Sensor 4 Serial Num", Description: ""},
				},
			},
		}})
}
