package model704

// Code generated by ../../generators/json/models.go. DO NOT EDIT.
// You can regenerate it by running 'make spec' from the project root.

import (
	"github.com/andig/gosunspec"
	"github.com/andig/gosunspec/typelabel"
	"github.com/andig/gosunspec/types"
)

// Block704 - DER AC Controls - DER AC controls model.

const (
	ModelID          = 704
	ModelLabel       = "DER AC Controls"
	ModelDescription = "DER AC controls model."
)

const (
	AntiIslEna        = "AntiIslEna"
	Ext               = "Ext"
	PF                = "PF"
	PFWAbsEna         = "PFWAbsEna"
	PFWAbsEnaRvrt     = "PFWAbsEnaRvrt"
	PFWAbsRvrtRem     = "PFWAbsRvrtRem"
	PFWAbsRvrtTms     = "PFWAbsRvrtTms"
	PFWInjEna         = "PFWInjEna"
	PFWInjEnaRvrt     = "PFWInjEnaRvrt"
	PFWInjRvrtRem     = "PFWInjRvrtRem"
	PFWInjRvrtTms     = "PFWInjRvrtTms"
	PF_SF             = "PF_SF"
	VarRmp            = "VarRmp"
	VarSet            = "VarSet"
	VarSetEna         = "VarSetEna"
	VarSetEnaRvrt     = "VarSetEnaRvrt"
	VarSetMod         = "VarSetMod"
	VarSetPct         = "VarSetPct"
	VarSetPctRvrt     = "VarSetPctRvrt"
	VarSetPct_SF      = "VarSetPct_SF"
	VarSetPri         = "VarSetPri"
	VarSetRvrt        = "VarSetRvrt"
	VarSetRvrtRem     = "VarSetRvrtRem"
	VarSetRvrtTms     = "VarSetRvrtTms"
	VarSet_SF         = "VarSet_SF"
	WMaxLimPct        = "WMaxLimPct"
	WMaxLimPctEna     = "WMaxLimPctEna"
	WMaxLimPctEnaRvrt = "WMaxLimPctEnaRvrt"
	WMaxLimPctRvrt    = "WMaxLimPctRvrt"
	WMaxLimPctRvrtRem = "WMaxLimPctRvrtRem"
	WMaxLimPctRvrtTms = "WMaxLimPctRvrtTms"
	WMaxLimPct_SF     = "WMaxLimPct_SF"
	WRmp              = "WRmp"
	WRmpRef           = "WRmpRef"
	WSet              = "WSet"
	WSetEna           = "WSetEna"
	WSetEnaRvrt       = "WSetEnaRvrt"
	WSetMod           = "WSetMod"
	WSetPct           = "WSetPct"
	WSetPctRvrt       = "WSetPctRvrt"
	WSetPct_SF        = "WSetPct_SF"
	WSetRvrt          = "WSetRvrt"
	WSetRvrtRem       = "WSetRvrtRem"
	WSetRvrtTms       = "WSetRvrtTms"
	WSet_SF           = "WSet_SF"
)

type Block704PFWInjRepeat struct {
	PF  uint16         `sunspec:"offset=0,sf=PF_SF,access=rw"`
	Ext sunspec.Enum16 `sunspec:"offset=1,access=rw"`
}

type Block704PFWInjRvrtRepeat struct {
	PF  uint16         `sunspec:"offset=0,sf=PF_SF,access=rw"`
	Ext sunspec.Enum16 `sunspec:"offset=1,access=rw"`
}

type Block704PFWAbsRepeat struct {
	PF  uint16         `sunspec:"offset=0,sf=PF_SF,access=rw"`
	Ext sunspec.Enum16 `sunspec:"offset=1,access=rw"`
}

type Block704PFWAbsRvrtRepeat struct {
	PF  uint16         `sunspec:"offset=0,sf=PF_SF,access=rw"`
	Ext sunspec.Enum16 `sunspec:"offset=1,access=rw"`
}

type Block704 struct {
	PFWInjEna         sunspec.Enum16      `sunspec:"offset=0,access=rw"`
	PFWInjEnaRvrt     sunspec.Enum16      `sunspec:"offset=1,access=rw"`
	PFWInjRvrtTms     uint32              `sunspec:"offset=2,access=rw"`
	PFWInjRvrtRem     uint32              `sunspec:"offset=4"`
	PFWAbsEna         sunspec.Enum16      `sunspec:"offset=6,access=rw"`
	PFWAbsEnaRvrt     sunspec.Enum16      `sunspec:"offset=7,access=rw"`
	PFWAbsRvrtTms     uint32              `sunspec:"offset=8,access=rw"`
	PFWAbsRvrtRem     uint32              `sunspec:"offset=10"`
	WMaxLimPctEna     sunspec.Enum16      `sunspec:"offset=12,access=rw"`
	WMaxLimPct        uint16              `sunspec:"offset=13,sf=WMaxLimPct_SF,access=rw"`
	WMaxLimPctRvrt    uint16              `sunspec:"offset=14,sf=WMaxLimPct_SF,access=rw"`
	WMaxLimPctEnaRvrt sunspec.Enum16      `sunspec:"offset=15,access=rw"`
	WMaxLimPctRvrtTms uint32              `sunspec:"offset=16,access=rw"`
	WMaxLimPctRvrtRem uint32              `sunspec:"offset=18"`
	WSetEna           sunspec.Enum16      `sunspec:"offset=20,access=rw"`
	WSetMod           sunspec.Enum16      `sunspec:"offset=21,access=rw"`
	WSet              int32               `sunspec:"offset=22,sf=WSet_SF,access=rw"`
	WSetRvrt          int32               `sunspec:"offset=24,sf=WSet_SF,access=rw"`
	WSetPct           int16               `sunspec:"offset=26,sf=WSetPct_SF,access=rw"`
	WSetPctRvrt       int16               `sunspec:"offset=27,sf=WSetPct_SF,access=rw"`
	WSetEnaRvrt       sunspec.Enum16      `sunspec:"offset=28,access=rw"`
	WSetRvrtTms       uint32              `sunspec:"offset=29,access=rw"`
	WSetRvrtRem       uint32              `sunspec:"offset=31"`
	VarSetEna         sunspec.Enum16      `sunspec:"offset=33,access=rw"`
	VarSetMod         sunspec.Enum16      `sunspec:"offset=34,access=rw"`
	VarSetPri         sunspec.Enum16      `sunspec:"offset=35,access=rw"`
	VarSet            int32               `sunspec:"offset=36,sf=VarSet_SF,access=rw"`
	VarSetRvrt        int32               `sunspec:"offset=38,sf=VarSet_SF,access=rw"`
	VarSetPct         int16               `sunspec:"offset=40,sf=VarSetPct_SF,access=rw"`
	VarSetPctRvrt     int16               `sunspec:"offset=41,sf=VarSetPct_SF,access=rw"`
	VarSetEnaRvrt     sunspec.Enum16      `sunspec:"offset=42,access=rw"`
	VarSetRvrtTms     uint32              `sunspec:"offset=43,access=rw"`
	VarSetRvrtRem     uint32              `sunspec:"offset=45"`
	WRmp              uint16              `sunspec:"offset=47,access=rw"`
	WRmpRef           sunspec.Enum16      `sunspec:"offset=48,access=rw"`
	VarRmp            uint16              `sunspec:"offset=49,access=rw"`
	AntiIslEna        sunspec.Enum16      `sunspec:"offset=50,access=rw"`
	PF_SF             sunspec.ScaleFactor `sunspec:"offset=51"`
	WMaxLimPct_SF     sunspec.ScaleFactor `sunspec:"offset=52"`
	WSet_SF           sunspec.ScaleFactor `sunspec:"offset=53"`
	WSetPct_SF        sunspec.ScaleFactor `sunspec:"offset=54"`
	VarSet_SF         sunspec.ScaleFactor `sunspec:"offset=55"`
	VarSetPct_SF      sunspec.ScaleFactor `sunspec:"offset=56"`

	PFWInj []Block704PFWInjRepeat

	PFWInjRvrt []Block704PFWInjRvrtRepeat

	PFWAbs []Block704PFWAbsRepeat

	PFWAbsRvrt []Block704PFWAbsRvrtRepeat
}

func (block *Block704) GetId() sunspec.ModelId {
	return ModelID
}

func init() {
	types.RegisterModel(&types.Model{
		Id:          ModelID,
		Name:        "DERCtlAC",
		Label:       "DER AC Controls",
		Description: "DER AC controls model.",
		Length:      65,
		Blocks: []types.Block{
			{
				Length: 57,
				Type:   types.BlockFixed,
				Points: []types.Point{
					{Id: PFWInjEna, Offset: 0, Type: typelabel.Enum16, Access: "rw", Label: "Power Factor Enable (W Inj) Enable", Description: "Power factor enable when injecting active power."},
					{Id: PFWInjEnaRvrt, Offset: 1, Type: typelabel.Enum16, Access: "rw", Label: "Power Factor Reversion Enable (W Inj)", Description: "Power factor reversion timer when injecting active power enable."},
					{Id: PFWInjRvrtTms, Offset: 2, Type: typelabel.Uint32, Units: "Secs", Access: "rw", Label: "PF Reversion Time (W Inj)", Description: "Power factor reversion timer when injecting active power."},
					{Id: PFWInjRvrtRem, Offset: 4, Type: typelabel.Uint32, Units: "Secs", Label: "PF Reversion Time Rem (W Inj)", Description: "Power factor reversion time remaining when injecting active power."},
					{Id: PFWAbsEna, Offset: 6, Type: typelabel.Enum16, Access: "rw", Label: "Power Factor Enable (W Abs) Enable", Description: "Power factor enable when absorbing active power."},
					{Id: PFWAbsEnaRvrt, Offset: 7, Type: typelabel.Enum16, Access: "rw", Label: "Power Factor Reversion Enable (W Abs)", Description: "Power factor reversion timer when absorbing active power enable."},
					{Id: PFWAbsRvrtTms, Offset: 8, Type: typelabel.Uint32, Units: "Secs", Access: "rw", Label: "PF Reversion Time (W Abs)", Description: "Power factor reversion timer when absorbing active power."},
					{Id: PFWAbsRvrtRem, Offset: 10, Type: typelabel.Uint32, Units: "Secs", Label: "PF Reversion Time Rem (W Abs)", Description: "Power factor reversion time remaining when absorbing active power."},
					{Id: WMaxLimPctEna, Offset: 12, Type: typelabel.Enum16, Access: "rw", Label: "Limit Max Power Pct Enable", Description: "Limit maximum active power percent enable."},
					{Id: WMaxLimPct, Offset: 13, Type: typelabel.Uint16, ScaleFactor: "WMaxLimPct_SF", Units: "Pct", Access: "rw", Label: "Limit Max Power Pct Setpoint", Description: "Limit maximum active power percent value."},
					{Id: WMaxLimPctRvrt, Offset: 14, Type: typelabel.Uint16, ScaleFactor: "WMaxLimPct_SF", Units: "Pct", Access: "rw", Label: "Reversion Limit Max Power Pct", Description: "Reversion limit maximum active power percent value."},
					{Id: WMaxLimPctEnaRvrt, Offset: 15, Type: typelabel.Enum16, Access: "rw", Label: "Reversion Limit Max Power Pct Enable", Description: "Reversion limit maximum active power percent value enable."},
					{Id: WMaxLimPctRvrtTms, Offset: 16, Type: typelabel.Uint32, Units: "Secs", Access: "rw", Label: "Limit Max Power Pct Reversion Time", Description: "Limit maximum active power percent reversion time."},
					{Id: WMaxLimPctRvrtRem, Offset: 18, Type: typelabel.Uint32, Units: "Secs", Label: "Limit Max Power Pct Rev Time Rem", Description: "Limit maximum active power percent reversion time remaining."},
					{Id: WSetEna, Offset: 20, Type: typelabel.Enum16, Access: "rw", Label: "Set Active Power Enable", Description: "Set active power enable."},
					{Id: WSetMod, Offset: 21, Type: typelabel.Enum16, Access: "rw", Label: "Set Active Power Mode", Description: "Set active power mode."},
					{Id: WSet, Offset: 22, Type: typelabel.Int32, ScaleFactor: "WSet_SF", Units: "W", Access: "rw", Label: "Active Power Setpoint (W)", Description: "Active power setting value in watts."},
					{Id: WSetRvrt, Offset: 24, Type: typelabel.Int32, ScaleFactor: "WSet_SF", Units: "W", Access: "rw", Label: "Reversion Active Power (W)", Description: "Reversion active power setting value in watts."},
					{Id: WSetPct, Offset: 26, Type: typelabel.Int16, ScaleFactor: "WSetPct_SF", Units: "Pct", Access: "rw", Label: "Active Power Setpoint (Pct)", Description: "Active power setting value as percent."},
					{Id: WSetPctRvrt, Offset: 27, Type: typelabel.Int16, ScaleFactor: "WSetPct_SF", Units: "Pct", Access: "rw", Label: "Reversion Active Power (Pct)", Description: "Reversion active power setting value as percent."},
					{Id: WSetEnaRvrt, Offset: 28, Type: typelabel.Enum16, Access: "rw", Label: "Reversion Active Power Enable", Description: "Reversion active power function enable."},
					{Id: WSetRvrtTms, Offset: 29, Type: typelabel.Uint32, Units: "Secs", Access: "rw", Label: "Active Power Reversion Time", Description: "Set active power reversion time."},
					{Id: WSetRvrtRem, Offset: 31, Type: typelabel.Uint32, Units: "Secs", Label: "Active Power Rev Time Rem", Description: "Set active power reversion time remaining."},
					{Id: VarSetEna, Offset: 33, Type: typelabel.Enum16, Access: "rw", Label: "Set Reactive Power Enable", Description: "Set reactive power enable."},
					{Id: VarSetMod, Offset: 34, Type: typelabel.Enum16, Access: "rw", Label: "Set Reactive Power Mode", Description: "Set reactive power mode."},
					{Id: VarSetPri, Offset: 35, Type: typelabel.Enum16, Access: "rw", Label: "Reactive Power Priority", Description: "Reactive power priority."},
					{Id: VarSet, Offset: 36, Type: typelabel.Int32, ScaleFactor: "VarSet_SF", Units: "Var", Access: "rw", Label: "Reactive Power Setpoint (Vars)", Description: "Reactive power setting value in vars."},
					{Id: VarSetRvrt, Offset: 38, Type: typelabel.Int32, ScaleFactor: "VarSet_SF", Units: "Var", Access: "rw", Label: "Reversion Reactive Power (Vars)", Description: "Reversion reactive power setting value in vars."},
					{Id: VarSetPct, Offset: 40, Type: typelabel.Int16, ScaleFactor: "VarSetPct_SF", Units: "Pct", Access: "rw", Label: "Reactive Power Setpoint (Pct)", Description: "Reactive power setting value as percent."},
					{Id: VarSetPctRvrt, Offset: 41, Type: typelabel.Int16, ScaleFactor: "VarSetPct_SF", Units: "Pct", Access: "rw", Label: "Reversion Reactive Power (Pct)", Description: "Reversion reactive power setting value as percent."},
					{Id: VarSetEnaRvrt, Offset: 42, Type: typelabel.Enum16, Access: "rw", Label: "Reversion Reactive Power Enable", Description: "Reversion reactive power function enable."},
					{Id: VarSetRvrtTms, Offset: 43, Type: typelabel.Uint32, Units: "Secs", Access: "rw", Label: "Reactive Power Reversion Time", Description: "Set reactive power reversion time."},
					{Id: VarSetRvrtRem, Offset: 45, Type: typelabel.Uint32, Units: "Secs", Label: "Reactive Power Rev Time Rem", Description: "Set reactive power reversion time remaining."},
					{Id: WRmp, Offset: 47, Type: typelabel.Uint16, Units: "%Max/Sec", Access: "rw", Label: "Normal Ramp Rate", Description: "Ramp rate for increases in active power during normal generation."},
					{Id: WRmpRef, Offset: 48, Type: typelabel.Enum16, Access: "rw", Label: "Normal Ramp Rate Reference", Description: "Ramp rate reference unit for increases in active power or current during normal generation."},
					{Id: VarRmp, Offset: 49, Type: typelabel.Uint16, Units: "%Max/Sec", Access: "rw", Label: "Reactive Power Ramp Rate", Description: "Ramp rate based on max reactive power per second."},
					{Id: AntiIslEna, Offset: 50, Type: typelabel.Enum16, Access: "rw", Label: "Anti-Islanding Enable", Description: "Anti-islanding enable."},
					{Id: PF_SF, Offset: 51, Type: typelabel.ScaleFactor, Label: "Power Factor Scale Factor", Description: "Power factor scale factor."},
					{Id: WMaxLimPct_SF, Offset: 52, Type: typelabel.ScaleFactor, Label: "Limit Max Power Scale Factor", Description: "Limit maximum power scale factor."},
					{Id: WSet_SF, Offset: 53, Type: typelabel.ScaleFactor, Label: "Active Power Scale Factor", Description: "Active power scale factor."},
					{Id: WSetPct_SF, Offset: 54, Type: typelabel.ScaleFactor, Label: "Active Power Pct Scale Factor", Description: "Active power pct scale factor."},
					{Id: VarSet_SF, Offset: 55, Type: typelabel.ScaleFactor, Label: "Reactive Power Scale Factor", Description: "Reactive power scale factor."},
					{Id: VarSetPct_SF, Offset: 56, Type: typelabel.ScaleFactor, Label: "Reactive Power Pct Scale Factor", Description: "Reactive power pct scale factor."},
				},
			},
			{Name: "PFWInj",
				Length: 2,
				Type:   types.BlockRepeating,
				Points: []types.Point{
					{Id: PF, Offset: 0, Type: typelabel.Uint16, ScaleFactor: "PF_SF", Access: "rw", Label: "Power Factor (W Inj) ", Description: "Power factor setpoint when injecting active power."},
					{Id: Ext, Offset: 1, Type: typelabel.Enum16, Access: "rw", Label: "Power Factor Excitation (W Inj)", Description: "Power factor excitation setpoint when injecting active power."},
				},
			},
			{Name: "PFWInjRvrt",
				Length: 2,
				Type:   types.BlockRepeating,
				Points: []types.Point{
					{Id: PF, Offset: 0, Type: typelabel.Uint16, ScaleFactor: "PF_SF", Access: "rw", Label: "Reversion Power Factor (W Inj) ", Description: "Reversion power factor setpoint when injecting active power."},
					{Id: Ext, Offset: 1, Type: typelabel.Enum16, Access: "rw", Label: "Reversion PF Excitation (W Inj)", Description: "Reversion power factor excitation setpoint when injecting active power."},
				},
			},
			{Name: "PFWAbs",
				Length: 2,
				Type:   types.BlockRepeating,
				Points: []types.Point{
					{Id: PF, Offset: 0, Type: typelabel.Uint16, ScaleFactor: "PF_SF", Access: "rw", Label: "Power Factor (W Abs) ", Description: "Power factor setpoint when absorbing active power."},
					{Id: Ext, Offset: 1, Type: typelabel.Enum16, Access: "rw", Label: "Power Factor Excitation (W Abs)", Description: "Power factor excitation setpoint when absorbing active power."},
				},
			},
			{Name: "PFWAbsRvrt",
				Length: 2,
				Type:   types.BlockRepeating,
				Points: []types.Point{
					{Id: PF, Offset: 0, Type: typelabel.Uint16, ScaleFactor: "PF_SF", Access: "rw", Label: "Reversion Power Factor (W Abs) ", Description: "Reversion power factor setpoint when absorbing active power."},
					{Id: Ext, Offset: 1, Type: typelabel.Enum16, Access: "rw", Label: "Reversion PF Excitation (W Abs)", Description: "Reversion power factor excitation setpoint when absorbing active power."},
				},
			},
		}})
}
