package model64413

// Code generated by ../../generators/json/models.go. DO NOT EDIT.
// You can regenerate it by running 'make spec' from the project root.

import (
	"github.com/andig/gosunspec"
	"github.com/andig/gosunspec/typelabel"
	"github.com/andig/gosunspec/types"
)

// Block64413 - PV Curves - Current-Voltage and Power-Voltage Profiles for PV Simulation.

const (
	ModelID          = 64413
	ModelLabel       = "PV Curves"
	ModelDescription = "Current-Voltage and Power-Voltage Profiles for PV Simulation."
)

const (
	I      = "I"
	IVLen  = "IVLen"
	Irr    = "Irr"
	Irr_SF = "Irr_SF"
	P      = "P"
	V      = "V"
)

type Block64413Repeat struct {
	P float32 `sunspec:"offset=0"`
	I float32 `sunspec:"offset=2"`
	V float32 `sunspec:"offset=4"`
}

type Block64413 struct {
	IVLen  sunspec.Count       `sunspec:"offset=0"`
	Irr    uint16              `sunspec:"offset=1,sf=Irr_SF"`
	Irr_SF sunspec.ScaleFactor `sunspec:"offset=2"`

	Repeats []Block64413Repeat
}

func (block *Block64413) GetId() sunspec.ModelId {
	return ModelID
}

func init() {
	types.RegisterModel(&types.Model{
		Id:          ModelID,
		Name:        "PVSimCurves",
		Label:       "PV Curves",
		Description: "Current-Voltage and Power-Voltage Profiles for PV Simulation.",
		Length:      9,
		Blocks: []types.Block{
			{
				Length: 3,
				Type:   types.BlockFixed,
				Points: []types.Point{
					{Id: IVLen, Offset: 0, Type: typelabel.Count, Label: "IV length", Description: "Number of points in the IV curve."},
					{Id: Irr, Offset: 1, Type: typelabel.Uint16, ScaleFactor: "Irr_SF", Units: "W/m^2", Label: "POA Irradiance", Description: "Plane of Array Irradiance"},
					{Id: Irr_SF, Offset: 2, Type: typelabel.ScaleFactor},
				},
			},
			{Name: "IV",
				Length: 6,
				Type:   types.BlockRepeating,
				Points: []types.Point{
					{Id: P, Offset: 0, Type: typelabel.Float32, Units: "W", Label: "Power", Description: "Power"},
					{Id: I, Offset: 2, Type: typelabel.Float32, Units: "A", Label: "Current", Description: "Current"},
					{Id: V, Offset: 4, Type: typelabel.Float32, Units: "V", Label: "Voltage", Description: "Voltage"},
				},
			},
		}})
}
