package model308

// Code generated by ../../generators/json/models.go. DO NOT EDIT.
// You can regenerate it by running 'make spec' from the project root.

import (
	"github.com/andig/gosunspec"
	"github.com/andig/gosunspec/typelabel"
	"github.com/andig/gosunspec/types"
)

// Block308 - Mini Met Model - Include to support a few basic measurements

const (
	ModelID          = 308
	ModelLabel       = "Mini Met Model"
	ModelDescription = "Include to support a few basic measurements"
)

const (
	GHI    = "GHI"
	TmpAmb = "TmpAmb"
	TmpBOM = "TmpBOM"
	WndSpd = "WndSpd"
)

type Block308 struct {
	GHI    uint16 `sunspec:"offset=0"`
	TmpBOM int16  `sunspec:"offset=1,sf=-1"`
	TmpAmb int16  `sunspec:"offset=2,sf=-1"`
	WndSpd uint16 `sunspec:"offset=3"`
}

func (block *Block308) GetId() sunspec.ModelId {
	return ModelID
}

func init() {
	types.RegisterModel(&types.Model{
		Id:          ModelID,
		Name:        "mini_met",
		Label:       "Mini Met Model",
		Description: "Include to support a few basic measurements",
		Length:      4,
		Blocks: []types.Block{
			{
				Length: 4,
				Type:   types.BlockFixed,
				Points: []types.Point{
					{Id: GHI, Offset: 0, Type: typelabel.Uint16, Units: "W/m2", Label: "GHI", Description: "Global Horizontal Irradiance"},
					{Id: TmpBOM, Offset: 1, Type: typelabel.Int16, ScaleFactor: "-1", Units: "C", Label: "Temp", Description: "Back of module temperature measurement"},
					{Id: TmpAmb, Offset: 2, Type: typelabel.Int16, ScaleFactor: "-1", Units: "C", Label: "Ambient Temperature", Description: ""},
					{Id: WndSpd, Offset: 3, Type: typelabel.Uint16, Units: "m/s", Label: "Wind Speed", Description: ""},
				},
			},
		}})
}
